// @generated by `rt addressables generate`; do not edit.

pub mod hearts {
  use battlement::SceneAddress;

  /// Addressable key `hearts/content` (UnityEditor.SceneAsset) from `Assets/Scenes/Content.unity` in group `Battlement Hearts`.
  pub const CONTENT: SceneAddress = SceneAddress::from_static("hearts/content");

  pub mod cards {
    use battlement::TextureAddress;

    /// Addressable key `hearts/cards/back` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/cardback_A.png` in group `Battlement Hearts`.
    pub const BACK: TextureAddress = TextureAddress::from_static("hearts/cards/back");

    pub mod clubs {
      use battlement::PrefabAddress;

      /// Addressable key `hearts/cards/clubs/ace` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_ace.fbx` in group `Battlement Hearts`.
      pub const ACE: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/ace");
      /// Addressable key `hearts/cards/clubs/eight` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_eight.fbx` in group `Battlement Hearts`.
      pub const EIGHT: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/eight");
      /// Addressable key `hearts/cards/clubs/five` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_five.fbx` in group `Battlement Hearts`.
      pub const FIVE: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/five");
      /// Addressable key `hearts/cards/clubs/four` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_four.fbx` in group `Battlement Hearts`.
      pub const FOUR: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/four");
      /// Addressable key `hearts/cards/clubs/jack` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_jack.fbx` in group `Battlement Hearts`.
      pub const JACK: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/jack");
      /// Addressable key `hearts/cards/clubs/king` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_king.fbx` in group `Battlement Hearts`.
      pub const KING: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/king");
      /// Addressable key `hearts/cards/clubs/nine` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_nine.fbx` in group `Battlement Hearts`.
      pub const NINE: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/nine");
      /// Addressable key `hearts/cards/clubs/queen` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_queen.fbx` in group `Battlement Hearts`.
      pub const QUEEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/queen");
      /// Addressable key `hearts/cards/clubs/seven` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_seven.fbx` in group `Battlement Hearts`.
      pub const SEVEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/seven");
      /// Addressable key `hearts/cards/clubs/six` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_six.fbx` in group `Battlement Hearts`.
      pub const SIX: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/six");
      /// Addressable key `hearts/cards/clubs/ten` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_ten.fbx` in group `Battlement Hearts`.
      pub const TEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/ten");
      /// Addressable key `hearts/cards/clubs/three` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_three.fbx` in group `Battlement Hearts`.
      pub const THREE: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/three");
      /// Addressable key `hearts/cards/clubs/two` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_clubs_two.fbx` in group `Battlement Hearts`.
      pub const TWO: PrefabAddress = PrefabAddress::from_static("hearts/cards/clubs/two");
    }

    pub mod diamonds {
      use battlement::PrefabAddress;

      /// Addressable key `hearts/cards/diamonds/ace` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_ace.fbx` in group `Battlement Hearts`.
      pub const ACE: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/ace");
      /// Addressable key `hearts/cards/diamonds/eight` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_eight.fbx` in group `Battlement Hearts`.
      pub const EIGHT: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/eight");
      /// Addressable key `hearts/cards/diamonds/five` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_five.fbx` in group `Battlement Hearts`.
      pub const FIVE: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/five");
      /// Addressable key `hearts/cards/diamonds/four` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_four.fbx` in group `Battlement Hearts`.
      pub const FOUR: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/four");
      /// Addressable key `hearts/cards/diamonds/jack` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_jack.fbx` in group `Battlement Hearts`.
      pub const JACK: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/jack");
      /// Addressable key `hearts/cards/diamonds/king` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_king.fbx` in group `Battlement Hearts`.
      pub const KING: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/king");
      /// Addressable key `hearts/cards/diamonds/nine` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_nine.fbx` in group `Battlement Hearts`.
      pub const NINE: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/nine");
      /// Addressable key `hearts/cards/diamonds/queen` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_queen.fbx` in group `Battlement Hearts`.
      pub const QUEEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/queen");
      /// Addressable key `hearts/cards/diamonds/seven` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_seven.fbx` in group `Battlement Hearts`.
      pub const SEVEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/seven");
      /// Addressable key `hearts/cards/diamonds/six` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_six.fbx` in group `Battlement Hearts`.
      pub const SIX: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/six");
      /// Addressable key `hearts/cards/diamonds/ten` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_ten.fbx` in group `Battlement Hearts`.
      pub const TEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/ten");
      /// Addressable key `hearts/cards/diamonds/three` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_three.fbx` in group `Battlement Hearts`.
      pub const THREE: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/three");
      /// Addressable key `hearts/cards/diamonds/two` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_diamonds_two.fbx` in group `Battlement Hearts`.
      pub const TWO: PrefabAddress = PrefabAddress::from_static("hearts/cards/diamonds/two");
    }

    pub mod hearts {
      use battlement::PrefabAddress;

      /// Addressable key `hearts/cards/hearts/ace` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_ace.fbx` in group `Battlement Hearts`.
      pub const ACE: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/ace");
      /// Addressable key `hearts/cards/hearts/eight` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_eight.fbx` in group `Battlement Hearts`.
      pub const EIGHT: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/eight");
      /// Addressable key `hearts/cards/hearts/five` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_five.fbx` in group `Battlement Hearts`.
      pub const FIVE: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/five");
      /// Addressable key `hearts/cards/hearts/four` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_four.fbx` in group `Battlement Hearts`.
      pub const FOUR: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/four");
      /// Addressable key `hearts/cards/hearts/jack` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_jack.fbx` in group `Battlement Hearts`.
      pub const JACK: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/jack");
      /// Addressable key `hearts/cards/hearts/king` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_king.fbx` in group `Battlement Hearts`.
      pub const KING: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/king");
      /// Addressable key `hearts/cards/hearts/nine` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_nine.fbx` in group `Battlement Hearts`.
      pub const NINE: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/nine");
      /// Addressable key `hearts/cards/hearts/queen` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_queen.fbx` in group `Battlement Hearts`.
      pub const QUEEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/queen");
      /// Addressable key `hearts/cards/hearts/seven` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_seven.fbx` in group `Battlement Hearts`.
      pub const SEVEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/seven");
      /// Addressable key `hearts/cards/hearts/six` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_six.fbx` in group `Battlement Hearts`.
      pub const SIX: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/six");
      /// Addressable key `hearts/cards/hearts/ten` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_ten.fbx` in group `Battlement Hearts`.
      pub const TEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/ten");
      /// Addressable key `hearts/cards/hearts/three` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_three.fbx` in group `Battlement Hearts`.
      pub const THREE: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/three");
      /// Addressable key `hearts/cards/hearts/two` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_hearts_two.fbx` in group `Battlement Hearts`.
      pub const TWO: PrefabAddress = PrefabAddress::from_static("hearts/cards/hearts/two");
    }

    pub mod spades {
      use battlement::PrefabAddress;

      /// Addressable key `hearts/cards/spades/ace` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_ace.fbx` in group `Battlement Hearts`.
      pub const ACE: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/ace");
      /// Addressable key `hearts/cards/spades/eight` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_eight.fbx` in group `Battlement Hearts`.
      pub const EIGHT: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/eight");
      /// Addressable key `hearts/cards/spades/five` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_five.fbx` in group `Battlement Hearts`.
      pub const FIVE: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/five");
      /// Addressable key `hearts/cards/spades/four` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_four.fbx` in group `Battlement Hearts`.
      pub const FOUR: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/four");
      /// Addressable key `hearts/cards/spades/jack` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_jack.fbx` in group `Battlement Hearts`.
      pub const JACK: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/jack");
      /// Addressable key `hearts/cards/spades/king` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_king.fbx` in group `Battlement Hearts`.
      pub const KING: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/king");
      /// Addressable key `hearts/cards/spades/nine` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_nine.fbx` in group `Battlement Hearts`.
      pub const NINE: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/nine");
      /// Addressable key `hearts/cards/spades/queen` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_queen.fbx` in group `Battlement Hearts`.
      pub const QUEEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/queen");
      /// Addressable key `hearts/cards/spades/seven` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_seven.fbx` in group `Battlement Hearts`.
      pub const SEVEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/seven");
      /// Addressable key `hearts/cards/spades/six` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_six.fbx` in group `Battlement Hearts`.
      pub const SIX: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/six");
      /// Addressable key `hearts/cards/spades/ten` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_ten.fbx` in group `Battlement Hearts`.
      pub const TEN: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/ten");
      /// Addressable key `hearts/cards/spades/three` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_three.fbx` in group `Battlement Hearts`.
      pub const THREE: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/three");
      /// Addressable key `hearts/cards/spades/two` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/PlayingCards/card_spades_two.fbx` in group `Battlement Hearts`.
      pub const TWO: PrefabAddress = PrefabAddress::from_static("hearts/cards/spades/two");
    }
  }

  pub mod faces {
    pub mod clubs {
      use battlement::TextureAddress;

      /// Addressable key `hearts/faces/clubs/ace` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_ace.png` in group `Battlement Hearts`.
      pub const ACE: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/ace");
      /// Addressable key `hearts/faces/clubs/eight` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_eight.png` in group `Battlement Hearts`.
      pub const EIGHT: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/eight");
      /// Addressable key `hearts/faces/clubs/five` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_five.png` in group `Battlement Hearts`.
      pub const FIVE: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/five");
      /// Addressable key `hearts/faces/clubs/four` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_four.png` in group `Battlement Hearts`.
      pub const FOUR: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/four");
      /// Addressable key `hearts/faces/clubs/jack` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_jack.png` in group `Battlement Hearts`.
      pub const JACK: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/jack");
      /// Addressable key `hearts/faces/clubs/king` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_king.png` in group `Battlement Hearts`.
      pub const KING: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/king");
      /// Addressable key `hearts/faces/clubs/nine` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_nine.png` in group `Battlement Hearts`.
      pub const NINE: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/nine");
      /// Addressable key `hearts/faces/clubs/queen` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_queen.png` in group `Battlement Hearts`.
      pub const QUEEN: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/queen");
      /// Addressable key `hearts/faces/clubs/seven` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_seven.png` in group `Battlement Hearts`.
      pub const SEVEN: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/seven");
      /// Addressable key `hearts/faces/clubs/six` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_six.png` in group `Battlement Hearts`.
      pub const SIX: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/six");
      /// Addressable key `hearts/faces/clubs/ten` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_ten.png` in group `Battlement Hearts`.
      pub const TEN: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/ten");
      /// Addressable key `hearts/faces/clubs/three` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_three.png` in group `Battlement Hearts`.
      pub const THREE: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/three");
      /// Addressable key `hearts/faces/clubs/two` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/clubs_two.png` in group `Battlement Hearts`.
      pub const TWO: TextureAddress = TextureAddress::from_static("hearts/faces/clubs/two");
    }

    pub mod diamonds {
      use battlement::TextureAddress;

      /// Addressable key `hearts/faces/diamonds/ace` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_ace.png` in group `Battlement Hearts`.
      pub const ACE: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/ace");
      /// Addressable key `hearts/faces/diamonds/eight` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_eight.png` in group `Battlement Hearts`.
      pub const EIGHT: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/eight");
      /// Addressable key `hearts/faces/diamonds/five` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_five.png` in group `Battlement Hearts`.
      pub const FIVE: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/five");
      /// Addressable key `hearts/faces/diamonds/four` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_four.png` in group `Battlement Hearts`.
      pub const FOUR: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/four");
      /// Addressable key `hearts/faces/diamonds/jack` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_jack.png` in group `Battlement Hearts`.
      pub const JACK: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/jack");
      /// Addressable key `hearts/faces/diamonds/king` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_king.png` in group `Battlement Hearts`.
      pub const KING: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/king");
      /// Addressable key `hearts/faces/diamonds/nine` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_nine.png` in group `Battlement Hearts`.
      pub const NINE: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/nine");
      /// Addressable key `hearts/faces/diamonds/queen` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_queen.png` in group `Battlement Hearts`.
      pub const QUEEN: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/queen");
      /// Addressable key `hearts/faces/diamonds/seven` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_seven.png` in group `Battlement Hearts`.
      pub const SEVEN: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/seven");
      /// Addressable key `hearts/faces/diamonds/six` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_six.png` in group `Battlement Hearts`.
      pub const SIX: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/six");
      /// Addressable key `hearts/faces/diamonds/ten` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_ten.png` in group `Battlement Hearts`.
      pub const TEN: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/ten");
      /// Addressable key `hearts/faces/diamonds/three` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_three.png` in group `Battlement Hearts`.
      pub const THREE: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/three");
      /// Addressable key `hearts/faces/diamonds/two` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/diamonds_two.png` in group `Battlement Hearts`.
      pub const TWO: TextureAddress = TextureAddress::from_static("hearts/faces/diamonds/two");
    }

    pub mod hearts {
      use battlement::TextureAddress;

      /// Addressable key `hearts/faces/hearts/ace` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_ace.png` in group `Battlement Hearts`.
      pub const ACE: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/ace");
      /// Addressable key `hearts/faces/hearts/eight` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_eight.png` in group `Battlement Hearts`.
      pub const EIGHT: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/eight");
      /// Addressable key `hearts/faces/hearts/five` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_five.png` in group `Battlement Hearts`.
      pub const FIVE: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/five");
      /// Addressable key `hearts/faces/hearts/four` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_four.png` in group `Battlement Hearts`.
      pub const FOUR: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/four");
      /// Addressable key `hearts/faces/hearts/jack` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_jack.png` in group `Battlement Hearts`.
      pub const JACK: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/jack");
      /// Addressable key `hearts/faces/hearts/king` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_king.png` in group `Battlement Hearts`.
      pub const KING: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/king");
      /// Addressable key `hearts/faces/hearts/nine` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_nine.png` in group `Battlement Hearts`.
      pub const NINE: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/nine");
      /// Addressable key `hearts/faces/hearts/queen` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_queen.png` in group `Battlement Hearts`.
      pub const QUEEN: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/queen");
      /// Addressable key `hearts/faces/hearts/seven` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_seven.png` in group `Battlement Hearts`.
      pub const SEVEN: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/seven");
      /// Addressable key `hearts/faces/hearts/six` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_six.png` in group `Battlement Hearts`.
      pub const SIX: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/six");
      /// Addressable key `hearts/faces/hearts/ten` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_ten.png` in group `Battlement Hearts`.
      pub const TEN: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/ten");
      /// Addressable key `hearts/faces/hearts/three` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_three.png` in group `Battlement Hearts`.
      pub const THREE: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/three");
      /// Addressable key `hearts/faces/hearts/two` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/hearts_two.png` in group `Battlement Hearts`.
      pub const TWO: TextureAddress = TextureAddress::from_static("hearts/faces/hearts/two");
    }

    pub mod spades {
      use battlement::TextureAddress;

      /// Addressable key `hearts/faces/spades/ace` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_ace.png` in group `Battlement Hearts`.
      pub const ACE: TextureAddress = TextureAddress::from_static("hearts/faces/spades/ace");
      /// Addressable key `hearts/faces/spades/eight` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_eight.png` in group `Battlement Hearts`.
      pub const EIGHT: TextureAddress = TextureAddress::from_static("hearts/faces/spades/eight");
      /// Addressable key `hearts/faces/spades/five` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_five.png` in group `Battlement Hearts`.
      pub const FIVE: TextureAddress = TextureAddress::from_static("hearts/faces/spades/five");
      /// Addressable key `hearts/faces/spades/four` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_four.png` in group `Battlement Hearts`.
      pub const FOUR: TextureAddress = TextureAddress::from_static("hearts/faces/spades/four");
      /// Addressable key `hearts/faces/spades/jack` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_jack.png` in group `Battlement Hearts`.
      pub const JACK: TextureAddress = TextureAddress::from_static("hearts/faces/spades/jack");
      /// Addressable key `hearts/faces/spades/king` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_king.png` in group `Battlement Hearts`.
      pub const KING: TextureAddress = TextureAddress::from_static("hearts/faces/spades/king");
      /// Addressable key `hearts/faces/spades/nine` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_nine.png` in group `Battlement Hearts`.
      pub const NINE: TextureAddress = TextureAddress::from_static("hearts/faces/spades/nine");
      /// Addressable key `hearts/faces/spades/queen` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_queen.png` in group `Battlement Hearts`.
      pub const QUEEN: TextureAddress = TextureAddress::from_static("hearts/faces/spades/queen");
      /// Addressable key `hearts/faces/spades/seven` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_seven.png` in group `Battlement Hearts`.
      pub const SEVEN: TextureAddress = TextureAddress::from_static("hearts/faces/spades/seven");
      /// Addressable key `hearts/faces/spades/six` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_six.png` in group `Battlement Hearts`.
      pub const SIX: TextureAddress = TextureAddress::from_static("hearts/faces/spades/six");
      /// Addressable key `hearts/faces/spades/ten` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_ten.png` in group `Battlement Hearts`.
      pub const TEN: TextureAddress = TextureAddress::from_static("hearts/faces/spades/ten");
      /// Addressable key `hearts/faces/spades/three` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_three.png` in group `Battlement Hearts`.
      pub const THREE: TextureAddress = TextureAddress::from_static("hearts/faces/spades/three");
      /// Addressable key `hearts/faces/spades/two` (UnityEngine.Texture2D) from `Assets/ThirdParty/KayKit/PlayingCards/spades_two.png` in group `Battlement Hearts`.
      pub const TWO: TextureAddress = TextureAddress::from_static("hearts/faces/spades/two");
    }
  }

  pub mod fonts {
    use battlement::UiFontAddress;

    /// Addressable key `hearts/fonts/control` (UnityEngine.TextCore.Text.FontAsset) from `Assets/ThirdParty/Fonts/Barlow Condensed 700 UI.asset` in group `Battlement Hearts`.
    pub const CONTROL: UiFontAddress = UiFontAddress::from_static("hearts/fonts/control");
  }

  pub mod forest {
    use battlement::PrefabAddress;

    /// Addressable key `hearts/forest/bush-1-a-color1` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/ForestNaturePack/Bush_1_A_Color1.fbx` in group `Battlement Hearts`.
    pub const BUSH_1_A_COLOR1: PrefabAddress =
      PrefabAddress::from_static("hearts/forest/bush-1-a-color1");
    /// Addressable key `hearts/forest/grass-1-a-color1` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/ForestNaturePack/Grass_1_A_Color1.fbx` in group `Battlement Hearts`.
    pub const GRASS_1_A_COLOR1: PrefabAddress =
      PrefabAddress::from_static("hearts/forest/grass-1-a-color1");
    /// Addressable key `hearts/forest/hill-4x2x2-color1` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/ForestNaturePack/Hill_4x2x2_Color1.fbx` in group `Battlement Hearts`.
    pub const HILL_4X2X2_COLOR1: PrefabAddress =
      PrefabAddress::from_static("hearts/forest/hill-4x2x2-color1");
    /// Addressable key `hearts/forest/rock-1-a-color1` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/ForestNaturePack/Rock_1_A_Color1.fbx` in group `Battlement Hearts`.
    pub const ROCK_1_A_COLOR1: PrefabAddress =
      PrefabAddress::from_static("hearts/forest/rock-1-a-color1");
    /// Addressable key `hearts/forest/tree-1-a-color1` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/ForestNaturePack/Tree_1_A_Color1.fbx` in group `Battlement Hearts`.
    pub const TREE_1_A_COLOR1: PrefabAddress =
      PrefabAddress::from_static("hearts/forest/tree-1-a-color1");
    /// Addressable key `hearts/forest/tree-2-a-color1` (UnityEngine.GameObject) from `Assets/ThirdParty/KayKit/ForestNaturePack/Tree_2_A_Color1.fbx` in group `Battlement Hearts`.
    pub const TREE_2_A_COLOR1: PrefabAddress =
      PrefabAddress::from_static("hearts/forest/tree-2-a-color1");
  }

  pub mod materials {
    use battlement::MaterialAddress;

    /// Addressable key `hearts/materials/clearing` (UnityEngine.Material) from `Assets/Generated/Imported/Clearing.mat` in group `Battlement Hearts`.
    pub const CLEARING: MaterialAddress = MaterialAddress::from_static("hearts/materials/clearing");
  }
}

use battlement::PreparedAsset;

/// Every generated address that maps directly to a prepared runtime asset.
pub const ASSET_CATALOG: &[PreparedAsset] = &[
  PreparedAsset::Texture(hearts::cards::BACK),
  PreparedAsset::Prefab(hearts::cards::clubs::ACE),
  PreparedAsset::Prefab(hearts::cards::clubs::EIGHT),
  PreparedAsset::Prefab(hearts::cards::clubs::FIVE),
  PreparedAsset::Prefab(hearts::cards::clubs::FOUR),
  PreparedAsset::Prefab(hearts::cards::clubs::JACK),
  PreparedAsset::Prefab(hearts::cards::clubs::KING),
  PreparedAsset::Prefab(hearts::cards::clubs::NINE),
  PreparedAsset::Prefab(hearts::cards::clubs::QUEEN),
  PreparedAsset::Prefab(hearts::cards::clubs::SEVEN),
  PreparedAsset::Prefab(hearts::cards::clubs::SIX),
  PreparedAsset::Prefab(hearts::cards::clubs::TEN),
  PreparedAsset::Prefab(hearts::cards::clubs::THREE),
  PreparedAsset::Prefab(hearts::cards::clubs::TWO),
  PreparedAsset::Prefab(hearts::cards::diamonds::ACE),
  PreparedAsset::Prefab(hearts::cards::diamonds::EIGHT),
  PreparedAsset::Prefab(hearts::cards::diamonds::FIVE),
  PreparedAsset::Prefab(hearts::cards::diamonds::FOUR),
  PreparedAsset::Prefab(hearts::cards::diamonds::JACK),
  PreparedAsset::Prefab(hearts::cards::diamonds::KING),
  PreparedAsset::Prefab(hearts::cards::diamonds::NINE),
  PreparedAsset::Prefab(hearts::cards::diamonds::QUEEN),
  PreparedAsset::Prefab(hearts::cards::diamonds::SEVEN),
  PreparedAsset::Prefab(hearts::cards::diamonds::SIX),
  PreparedAsset::Prefab(hearts::cards::diamonds::TEN),
  PreparedAsset::Prefab(hearts::cards::diamonds::THREE),
  PreparedAsset::Prefab(hearts::cards::diamonds::TWO),
  PreparedAsset::Prefab(hearts::cards::hearts::ACE),
  PreparedAsset::Prefab(hearts::cards::hearts::EIGHT),
  PreparedAsset::Prefab(hearts::cards::hearts::FIVE),
  PreparedAsset::Prefab(hearts::cards::hearts::FOUR),
  PreparedAsset::Prefab(hearts::cards::hearts::JACK),
  PreparedAsset::Prefab(hearts::cards::hearts::KING),
  PreparedAsset::Prefab(hearts::cards::hearts::NINE),
  PreparedAsset::Prefab(hearts::cards::hearts::QUEEN),
  PreparedAsset::Prefab(hearts::cards::hearts::SEVEN),
  PreparedAsset::Prefab(hearts::cards::hearts::SIX),
  PreparedAsset::Prefab(hearts::cards::hearts::TEN),
  PreparedAsset::Prefab(hearts::cards::hearts::THREE),
  PreparedAsset::Prefab(hearts::cards::hearts::TWO),
  PreparedAsset::Prefab(hearts::cards::spades::ACE),
  PreparedAsset::Prefab(hearts::cards::spades::EIGHT),
  PreparedAsset::Prefab(hearts::cards::spades::FIVE),
  PreparedAsset::Prefab(hearts::cards::spades::FOUR),
  PreparedAsset::Prefab(hearts::cards::spades::JACK),
  PreparedAsset::Prefab(hearts::cards::spades::KING),
  PreparedAsset::Prefab(hearts::cards::spades::NINE),
  PreparedAsset::Prefab(hearts::cards::spades::QUEEN),
  PreparedAsset::Prefab(hearts::cards::spades::SEVEN),
  PreparedAsset::Prefab(hearts::cards::spades::SIX),
  PreparedAsset::Prefab(hearts::cards::spades::TEN),
  PreparedAsset::Prefab(hearts::cards::spades::THREE),
  PreparedAsset::Prefab(hearts::cards::spades::TWO),
  PreparedAsset::Scene(hearts::CONTENT),
  PreparedAsset::Texture(hearts::faces::clubs::ACE),
  PreparedAsset::Texture(hearts::faces::clubs::EIGHT),
  PreparedAsset::Texture(hearts::faces::clubs::FIVE),
  PreparedAsset::Texture(hearts::faces::clubs::FOUR),
  PreparedAsset::Texture(hearts::faces::clubs::JACK),
  PreparedAsset::Texture(hearts::faces::clubs::KING),
  PreparedAsset::Texture(hearts::faces::clubs::NINE),
  PreparedAsset::Texture(hearts::faces::clubs::QUEEN),
  PreparedAsset::Texture(hearts::faces::clubs::SEVEN),
  PreparedAsset::Texture(hearts::faces::clubs::SIX),
  PreparedAsset::Texture(hearts::faces::clubs::TEN),
  PreparedAsset::Texture(hearts::faces::clubs::THREE),
  PreparedAsset::Texture(hearts::faces::clubs::TWO),
  PreparedAsset::Texture(hearts::faces::diamonds::ACE),
  PreparedAsset::Texture(hearts::faces::diamonds::EIGHT),
  PreparedAsset::Texture(hearts::faces::diamonds::FIVE),
  PreparedAsset::Texture(hearts::faces::diamonds::FOUR),
  PreparedAsset::Texture(hearts::faces::diamonds::JACK),
  PreparedAsset::Texture(hearts::faces::diamonds::KING),
  PreparedAsset::Texture(hearts::faces::diamonds::NINE),
  PreparedAsset::Texture(hearts::faces::diamonds::QUEEN),
  PreparedAsset::Texture(hearts::faces::diamonds::SEVEN),
  PreparedAsset::Texture(hearts::faces::diamonds::SIX),
  PreparedAsset::Texture(hearts::faces::diamonds::TEN),
  PreparedAsset::Texture(hearts::faces::diamonds::THREE),
  PreparedAsset::Texture(hearts::faces::diamonds::TWO),
  PreparedAsset::Texture(hearts::faces::hearts::ACE),
  PreparedAsset::Texture(hearts::faces::hearts::EIGHT),
  PreparedAsset::Texture(hearts::faces::hearts::FIVE),
  PreparedAsset::Texture(hearts::faces::hearts::FOUR),
  PreparedAsset::Texture(hearts::faces::hearts::JACK),
  PreparedAsset::Texture(hearts::faces::hearts::KING),
  PreparedAsset::Texture(hearts::faces::hearts::NINE),
  PreparedAsset::Texture(hearts::faces::hearts::QUEEN),
  PreparedAsset::Texture(hearts::faces::hearts::SEVEN),
  PreparedAsset::Texture(hearts::faces::hearts::SIX),
  PreparedAsset::Texture(hearts::faces::hearts::TEN),
  PreparedAsset::Texture(hearts::faces::hearts::THREE),
  PreparedAsset::Texture(hearts::faces::hearts::TWO),
  PreparedAsset::Texture(hearts::faces::spades::ACE),
  PreparedAsset::Texture(hearts::faces::spades::EIGHT),
  PreparedAsset::Texture(hearts::faces::spades::FIVE),
  PreparedAsset::Texture(hearts::faces::spades::FOUR),
  PreparedAsset::Texture(hearts::faces::spades::JACK),
  PreparedAsset::Texture(hearts::faces::spades::KING),
  PreparedAsset::Texture(hearts::faces::spades::NINE),
  PreparedAsset::Texture(hearts::faces::spades::QUEEN),
  PreparedAsset::Texture(hearts::faces::spades::SEVEN),
  PreparedAsset::Texture(hearts::faces::spades::SIX),
  PreparedAsset::Texture(hearts::faces::spades::TEN),
  PreparedAsset::Texture(hearts::faces::spades::THREE),
  PreparedAsset::Texture(hearts::faces::spades::TWO),
  PreparedAsset::UiFont(hearts::fonts::CONTROL),
  PreparedAsset::Prefab(hearts::forest::BUSH_1_A_COLOR1),
  PreparedAsset::Prefab(hearts::forest::GRASS_1_A_COLOR1),
  PreparedAsset::Prefab(hearts::forest::HILL_4X2X2_COLOR1),
  PreparedAsset::Prefab(hearts::forest::ROCK_1_A_COLOR1),
  PreparedAsset::Prefab(hearts::forest::TREE_1_A_COLOR1),
  PreparedAsset::Prefab(hearts::forest::TREE_2_A_COLOR1),
  PreparedAsset::Material(hearts::materials::CLEARING),
];
