//! Deterministic source manifests for immutable Ditto player builds.

use std::{
  collections::{BTreeMap, BTreeSet},
  fs::{self, File},
  io::{BufReader, Read},
  path::{Component, Path, PathBuf},
};

use anyhow::{Context, Result, ensure};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::fingerprint_rust;

const EXCLUDED_DIRECTORIES: &[&str] = &[".git", ".worktrees", ".ditto", "obj", "target"];

/// Filesystem path comparison used for collision detection and sorting.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CaseSensitivity {
  Sensitive,
  Insensitive,
}

/// Generated bytes that directly affect a player build.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedInput {
  pub generator: String,
  pub version: String,
  pub name: String,
  pub bytes: Vec<u8>,
}

/// Conservative source roots for one player.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FingerprintRequest {
  pub repository: PathBuf,
  pub unity_project: PathBuf,
  pub rust_manifest: PathBuf,
  pub generated_inputs: Vec<GeneratedInput>,
  pub case_sensitivity: CaseSensitivity,
}

/// How one source-manifest entry supplies bytes.
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum SourceKind {
  File,
  Generated,
}

/// One retained source input suitable for nearest-build diagnostics.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ManifestEntry {
  pub path: String,
  pub kind: SourceKind,
  pub mode: u32,
  pub bytes: u64,
  pub sha256: String,
}

/// Sorted source inputs and their complete aggregate fingerprint.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SourceManifest {
  pub fingerprint: String,
  pub entries: Vec<ManifestEntry>,
}

/// Paths changed relative to a retained nearest build.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct ManifestDiff {
  pub added: Vec<String>,
  pub removed: Vec<String>,
  pub changed: Vec<String>,
}

impl SourceManifest {
  /// Walks current working-tree bytes without consulting Git identity or timestamps.
  pub fn build(request: &FingerprintRequest) -> Result<Self> {
    let repository = request.repository.canonicalize()?;
    ensure!(repository.is_dir(), "repository is not a directory");
    let unity_project = checked_directory(&repository, &request.unity_project)?;
    let rust_manifest = checked_file(&repository, &request.rust_manifest)?;
    let mut candidates = Candidates::new(request.case_sensitivity);
    for root in ["Assets", "Packages", "ProjectSettings"] {
      let path = unity_project.join(root);
      if path.exists() {
        collect_tree(&repository, &path, &mut candidates)?;
      }
    }
    for package in unity_local_packages(&repository, &unity_project)? {
      collect_tree(&repository, &package, &mut candidates)?;
    }
    let manifests = fingerprint_rust::manifests(&repository, &rust_manifest)?;
    for manifest in &manifests {
      collect_tree(
        &repository,
        manifest.parent().expect("manifest has a parent"),
        &mut candidates,
      )?;
    }
    for path in fingerprint_rust::applicable_support_files(&repository, &manifests) {
      collect_file(&repository, &path, &mut candidates)?;
    }
    for input in &request.generated_inputs {
      collect_generated(input, &mut candidates)?;
    }
    build_manifest(candidates)
  }

  /// Serializes a retained manifest as stable pretty JSON with a final newline.
  pub fn to_json(&self) -> Result<Vec<u8>> {
    let mut bytes = serde_json::to_vec_pretty(self)?;
    bytes.push(b'\n');
    Ok(bytes)
  }

  /// Writes the retained nearest-build diagnostic manifest.
  pub fn write(&self, path: &Path) -> Result<()> {
    fs::write(path, self.to_json()?).with_context(|| format!("write {}", path.display()))
  }

  /// Loads a retained manifest and validates its ordering and digests.
  pub fn read(path: &Path) -> Result<Self> {
    let manifest: Self = serde_json::from_slice(&fs::read(path)?)?;
    validate_manifest(&manifest)?;
    Ok(manifest)
  }

  /// Names added, removed, and byte-or-mode-changed inputs.
  pub fn difference(&self, previous: &Self) -> ManifestDiff {
    let current = self
      .entries
      .iter()
      .map(|entry| (entry.path.as_str(), entry))
      .collect::<BTreeMap<_, _>>();
    let previous = previous
      .entries
      .iter()
      .map(|entry| (entry.path.as_str(), entry))
      .collect::<BTreeMap<_, _>>();
    ManifestDiff {
      added: current
        .keys()
        .filter(|path| !previous.contains_key(**path))
        .map(|path| (*path).to_owned())
        .collect(),
      removed: previous
        .keys()
        .filter(|path| !current.contains_key(**path))
        .map(|path| (*path).to_owned())
        .collect(),
      changed: current
        .iter()
        .filter(|(path, entry)| previous.get(**path).is_some_and(|old| *old != **entry))
        .map(|(path, _)| (*path).to_owned())
        .collect(),
    }
  }
}

#[derive(Debug)]
enum Candidate {
  File {
    path: String,
    physical: PathBuf,
    mode: u32,
  },
  Generated {
    path: String,
    bytes: Vec<u8>,
  },
}

#[derive(Debug)]
struct Candidates {
  sensitivity: CaseSensitivity,
  paths: BTreeMap<String, Candidate>,
  collisions: BTreeMap<String, String>,
}

impl Candidates {
  fn new(sensitivity: CaseSensitivity) -> Self {
    Self {
      sensitivity,
      paths: BTreeMap::new(),
      collisions: BTreeMap::new(),
    }
  }

  fn insert(&mut self, candidate: Candidate) -> Result<()> {
    let path = candidate_path(&candidate);
    let collision = collision_key(path, self.sensitivity);
    if let Some(existing) = self.collisions.get(&collision) {
      ensure!(existing == path, "source paths collide by case");
      return Ok(());
    }
    self.collisions.insert(collision, path.to_owned());
    self.paths.insert(path.to_owned(), candidate);
    Ok(())
  }
}

fn checked_directory(repository: &Path, path: &Path) -> Result<PathBuf> {
  ensure!(
    !fs::symlink_metadata(path)?.file_type().is_symlink(),
    "source root is a symlink"
  );
  let path = path.canonicalize()?;
  ensure!(
    path.starts_with(repository),
    "source root escapes repository"
  );
  ensure!(path.is_dir(), "source root is not a directory");
  Ok(path)
}

fn checked_file(repository: &Path, path: &Path) -> Result<PathBuf> {
  ensure!(
    !fs::symlink_metadata(path)?.file_type().is_symlink(),
    "source manifest is a symlink"
  );
  let path = path.canonicalize()?;
  ensure!(
    path.starts_with(repository),
    "source manifest escapes repository"
  );
  ensure!(path.is_file(), "source manifest is not a file");
  Ok(path)
}

fn collect_tree(repository: &Path, directory: &Path, candidates: &mut Candidates) -> Result<()> {
  for entry in fs::read_dir(directory).with_context(|| format!("read {}", directory.display()))? {
    let entry = entry?;
    let path = entry.path();
    if excluded(&path) {
      continue;
    }
    let file_type = entry.file_type()?;
    if file_type.is_dir() {
      collect_tree(repository, &path, candidates)?;
    } else if file_type.is_file() || file_type.is_symlink() {
      collect_file(repository, &path, candidates)?;
    }
  }
  Ok(())
}

fn collect_file(repository: &Path, logical_path: &Path, candidates: &mut Candidates) -> Result<()> {
  let metadata = fs::symlink_metadata(logical_path)?;
  let physical = if metadata.file_type().is_symlink() {
    let target = logical_path.canonicalize()?;
    ensure!(
      target.starts_with(repository),
      "source symlink escapes repository"
    );
    ensure!(target.is_file(), "source directory symlinks are ambiguous");
    target
  } else {
    ensure!(metadata.is_file(), "source input is not a regular file");
    logical_path.to_owned()
  };
  let path = normalized_path(repository, logical_path)?;
  candidates.insert(Candidate::File {
    path,
    mode: file_mode(&physical)?,
    physical,
  })
}

fn collect_generated(input: &GeneratedInput, candidates: &mut Candidates) -> Result<()> {
  ensure!(
    !input.generator.is_empty(),
    "generated input has no generator"
  );
  ensure!(!input.version.is_empty(), "generated input has no version");
  ensure!(!input.name.is_empty(), "generated input has no name");
  let path = format!(
    "@generated/{}/{}/{}",
    encode_segment(&input.generator),
    encode_segment(&input.version),
    encode_segment(&input.name)
  );
  candidates.insert(Candidate::Generated {
    path,
    bytes: input.bytes.clone(),
  })
}

fn build_manifest(candidates: Candidates) -> Result<SourceManifest> {
  let mut aggregate = Sha256::new();
  aggregate.update(b"battlement-source-v1\0");
  let mut entries = Vec::with_capacity(candidates.paths.len());
  for candidate in candidates.paths.into_values() {
    let (path, kind, mode, bytes, sha256) = hash_candidate(&mut aggregate, candidate)?;
    entries.push(ManifestEntry {
      path,
      kind,
      mode,
      bytes,
      sha256,
    });
  }
  Ok(SourceManifest {
    fingerprint: hexadecimal(&aggregate.finalize()),
    entries,
  })
}

fn hash_candidate(
  aggregate: &mut Sha256,
  candidate: Candidate,
) -> Result<(String, SourceKind, u32, u64, String)> {
  let (path, kind, mode, bytes, physical) = match candidate {
    Candidate::File {
      path,
      physical,
      mode,
    } => {
      let bytes = physical.metadata()?.len();
      (path, SourceKind::File, mode, bytes, Some(physical))
    }
    Candidate::Generated { path, bytes } => {
      let length = bytes.len() as u64;
      hash_header(aggregate, &path, SourceKind::Generated, 0, length);
      let mut digest = Sha256::new();
      digest.update(&bytes);
      aggregate.update(&bytes);
      return Ok((
        path,
        SourceKind::Generated,
        0,
        length,
        hexadecimal(&digest.finalize()),
      ));
    }
  };
  hash_header(aggregate, &path, kind, mode, bytes);
  let mut digest = Sha256::new();
  let mut reader = BufReader::new(File::open(physical.expect("file candidate has a path"))?);
  let mut buffer = [0_u8; 64 * 1024];
  loop {
    let read = reader.read(&mut buffer)?;
    if read == 0 {
      break;
    }
    digest.update(&buffer[..read]);
    aggregate.update(&buffer[..read]);
  }
  Ok((path, kind, mode, bytes, hexadecimal(&digest.finalize())))
}

fn hash_header(digest: &mut Sha256, path: &str, kind: SourceKind, mode: u32, bytes: u64) {
  digest.update([match kind {
    SourceKind::File => 0,
    SourceKind::Generated => 1,
  }]);
  digest.update((path.len() as u64).to_be_bytes());
  digest.update(path.as_bytes());
  digest.update(mode.to_be_bytes());
  digest.update(bytes.to_be_bytes());
}

fn unity_local_packages(repository: &Path, unity_project: &Path) -> Result<Vec<PathBuf>> {
  let manifest_path = unity_project.join("Packages/manifest.json");
  if !manifest_path.is_file() {
    return Ok(Vec::new());
  }
  let manifest: serde_json::Value = serde_json::from_slice(&fs::read(&manifest_path)?)?;
  let mut packages = BTreeSet::new();
  let dependencies = manifest
    .get("dependencies")
    .and_then(serde_json::Value::as_object)
    .ok_or_else(|| anyhow::anyhow!("Unity manifest has no dependencies object"))?;
  for value in dependencies.values().filter_map(serde_json::Value::as_str) {
    let Some(relative) = value.strip_prefix("file:") else {
      continue;
    };
    let path = manifest_path
      .parent()
      .expect("Unity manifest has a parent")
      .join(relative);
    ensure!(
      !fs::symlink_metadata(&path)?.file_type().is_symlink(),
      "local Unity package is a directory symlink"
    );
    let path = path.canonicalize()?;
    ensure!(
      path.starts_with(repository),
      "local Unity package escapes repository"
    );
    ensure!(path.is_dir(), "local Unity package is not a directory");
    packages.insert(path);
  }
  Ok(packages.into_iter().collect())
}

fn normalized_path(repository: &Path, path: &Path) -> Result<String> {
  let relative = path.strip_prefix(repository)?;
  ensure!(
    !relative.as_os_str().is_empty(),
    "source input path is empty"
  );
  let value = relative
    .to_str()
    .ok_or_else(|| anyhow::anyhow!("source path is not UTF-8"))?
    .replace('\\', "/");
  ensure!(!value.contains('\0'), "source path contains NUL");
  Ok(value)
}

fn excluded(path: &Path) -> bool {
  path.components().any(|component| match component {
    Component::Normal(name) => EXCLUDED_DIRECTORIES
      .iter()
      .any(|excluded| name == *excluded),
    _ => false,
  })
}

fn collision_key(path: &str, sensitivity: CaseSensitivity) -> String {
  match sensitivity {
    CaseSensitivity::Sensitive => path.to_owned(),
    CaseSensitivity::Insensitive => path.to_lowercase(),
  }
}

fn candidate_path(candidate: &Candidate) -> &str {
  match candidate {
    Candidate::File { path, .. } | Candidate::Generated { path, .. } => path,
  }
}

fn encode_segment(value: &str) -> String {
  value
    .bytes()
    .map(|byte| {
      if byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.') {
        (byte as char).to_string()
      } else {
        format!("%{byte:02X}")
      }
    })
    .collect()
}

fn validate_manifest(manifest: &SourceManifest) -> Result<()> {
  ensure!(
    valid_sha256(&manifest.fingerprint),
    "invalid source fingerprint"
  );
  ensure!(
    manifest
      .entries
      .windows(2)
      .all(|pair| pair[0].path < pair[1].path),
    "manifest entries are not unique and sorted"
  );
  for entry in &manifest.entries {
    ensure!(!entry.path.is_empty(), "manifest path is empty");
    ensure!(valid_sha256(&entry.sha256), "invalid manifest entry digest");
  }
  Ok(())
}

fn valid_sha256(value: &str) -> bool {
  value.len() == 64
    && value
      .bytes()
      .all(|byte| byte.is_ascii_hexdigit() && !byte.is_ascii_uppercase())
}

fn hexadecimal(bytes: &[u8]) -> String {
  bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

#[cfg(unix)]
fn file_mode(path: &Path) -> Result<u32> {
  use std::os::unix::fs::PermissionsExt;

  Ok(path.metadata()?.permissions().mode() & 0o777)
}

#[cfg(not(unix))]
fn file_mode(path: &Path) -> Result<u32> {
  Ok(if path.metadata()?.permissions().readonly() {
    0o444
  } else {
    0o644
  })
}
