#define ENABLE_SPAN_T
#define UNSAFE_BYTEBUFFER
// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Battlement.FlatBuffers.FixtureGenerated
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public enum FixtureError : byte
{
  Rejected = 0,
  Delayed = 1,
};

public enum FixtureClientBody : byte
{
  NONE = 0,
  Battlement_FlatBuffers_Generated_CoreAction = 1,
  Battlement_FlatBuffers_Generated_BatchFailed = 2,
  Battlement_FlatBuffers_Generated_OperationFailed = 3,
  FixtureAction = 4,
  FixtureBatchFailed = 5,
  FixtureOperationFailed = 6,
};



static public class FixtureClientBodyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((FixtureClientBody)typeId)
    {
      case FixtureClientBody.Battlement_FlatBuffers_Generated_CoreAction:
        result = Battlement.FlatBuffers.Generated.CoreActionVerify.Verify(verifier, tablePos);
        break;
      case FixtureClientBody.Battlement_FlatBuffers_Generated_BatchFailed:
        result = Battlement.FlatBuffers.Generated.BatchFailedVerify.Verify(verifier, tablePos);
        break;
      case FixtureClientBody.Battlement_FlatBuffers_Generated_OperationFailed:
        result = Battlement.FlatBuffers.Generated.OperationFailedVerify.Verify(verifier, tablePos);
        break;
      case FixtureClientBody.FixtureAction:
        result = Battlement.FlatBuffers.FixtureGenerated.FixtureActionVerify.Verify(verifier, tablePos);
        break;
      case FixtureClientBody.FixtureBatchFailed:
        result = Battlement.FlatBuffers.FixtureGenerated.FixtureBatchFailedVerify.Verify(verifier, tablePos);
        break;
      case FixtureClientBody.FixtureOperationFailed:
        result = Battlement.FlatBuffers.FixtureGenerated.FixtureOperationFailedVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

public enum FixtureCommand : byte
{
  NONE = 0,
  Battlement_FlatBuffers_Generated_CoreCommand = 1,
  FlashCommand = 2,
};



static public class FixtureCommandVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((FixtureCommand)typeId)
    {
      case FixtureCommand.Battlement_FlatBuffers_Generated_CoreCommand:
        result = Battlement.FlatBuffers.Generated.CoreCommandVerify.Verify(verifier, tablePos);
        break;
      case FixtureCommand.FlashCommand:
        result = Battlement.FlatBuffers.FixtureGenerated.FlashCommandVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

public enum ResponseMessage : byte
{
  NONE = 0,
  Battlement_FlatBuffers_Generated_Snapshot = 1,
  Batch = 2,
};



static public class ResponseMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((ResponseMessage)typeId)
    {
      case ResponseMessage.Battlement_FlatBuffers_Generated_Snapshot:
        result = Battlement.FlatBuffers.Generated.SnapshotVerify.Verify(verifier, tablePos);
        break;
      case ResponseMessage.Batch:
        result = Battlement.FlatBuffers.FixtureGenerated.BatchVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

public struct FlashPayload : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static FlashPayload GetRootAsFlashPayload(ByteBuffer _bb) { return GetRootAsFlashPayload(_bb, new FlashPayload()); }
  public static FlashPayload GetRootAsFlashPayload(ByteBuffer _bb, FlashPayload obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FlashPayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.Generated.Uuid? ObjectId { get { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float Scale { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static void StartFlashPayload(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddObjectId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> objectIdOffset) { builder.AddStruct(0, objectIdOffset.Value, 0); }
  public static void AddScale(FlatBufferBuilder builder, float scale) { builder.AddFloat(1, scale, 0.0f); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.FlashPayload> EndFlashPayload(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // object_id
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.FlashPayload>(o);
  }
}


static public class FlashPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ObjectId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyField(tablePos, 6 /*Scale*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct FlashCommand : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static FlashCommand GetRootAsFlashCommand(ByteBuffer _bb) { return GetRootAsFlashCommand(_bb, new FlashCommand()); }
  public static FlashCommand GetRootAsFlashCommand(ByteBuffer _bb, FlashCommand obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FlashCommand __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.Generated.Uuid? CommandId { get { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public bool Blocking { get { int o = __p.__offset(6); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)true; } }
  public string CommandType { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCommandTypeBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetCommandTypeBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetCommandTypeArray() { return __p.__vector_as_array<byte>(8); }
  public Battlement.FlatBuffers.FixtureGenerated.FlashPayload? Payload { get { int o = __p.__offset(10); return o != 0 ? (Battlement.FlatBuffers.FixtureGenerated.FlashPayload?)(new Battlement.FlatBuffers.FixtureGenerated.FlashPayload()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static void StartFlashCommand(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddCommandId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> commandIdOffset) { builder.AddStruct(0, commandIdOffset.Value, 0); }
  public static void AddBlocking(FlatBufferBuilder builder, bool blocking) { builder.AddBool(1, blocking, true); }
  public static void AddCommandType(FlatBufferBuilder builder, StringOffset commandTypeOffset) { builder.AddOffset(2, commandTypeOffset.Value, 0); }
  public static void AddPayload(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.FixtureGenerated.FlashPayload> payloadOffset) { builder.AddOffset(3, payloadOffset.Value, 0); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.FlashCommand> EndFlashCommand(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // command_id
    builder.Required(o, 8);  // command_type
    builder.Required(o, 10);  // payload
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.FlashCommand>(o);
  }
}


static public class FlashCommandVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*CommandId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyField(tablePos, 6 /*Blocking*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 8 /*CommandType*/, true)
      && verifier.VerifyTable(tablePos, 10 /*Payload*/, Battlement.FlatBuffers.FixtureGenerated.FlashPayloadVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct FixtureAction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static FixtureAction GetRootAsFixtureAction(ByteBuffer _bb) { return GetRootAsFixtureAction(_bb, new FixtureAction()); }
  public static FixtureAction GetRootAsFixtureAction(ByteBuffer _bb, FixtureAction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FixtureAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.Generated.Uuid? ActionId { get { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.Generated.Uuid? SessionId { get { int o = __p.__offset(6); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public string ActionType { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetActionTypeBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetActionTypeBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetActionTypeArray() { return __p.__vector_as_array<byte>(8); }
  public Battlement.FlatBuffers.FixtureGenerated.FlashPayload? Payload { get { int o = __p.__offset(10); return o != 0 ? (Battlement.FlatBuffers.FixtureGenerated.FlashPayload?)(new Battlement.FlatBuffers.FixtureGenerated.FlashPayload()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static void StartFixtureAction(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddActionId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> actionIdOffset) { builder.AddStruct(0, actionIdOffset.Value, 0); }
  public static void AddSessionId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> sessionIdOffset) { builder.AddStruct(1, sessionIdOffset.Value, 0); }
  public static void AddActionType(FlatBufferBuilder builder, StringOffset actionTypeOffset) { builder.AddOffset(2, actionTypeOffset.Value, 0); }
  public static void AddPayload(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.FixtureGenerated.FlashPayload> payloadOffset) { builder.AddOffset(3, payloadOffset.Value, 0); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.FixtureAction> EndFixtureAction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // action_id
    builder.Required(o, 6);  // session_id
    builder.Required(o, 8);  // action_type
    builder.Required(o, 10);  // payload
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.FixtureAction>(o);
  }
}


static public class FixtureActionVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ActionId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyField(tablePos, 6 /*SessionId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyString(tablePos, 8 /*ActionType*/, true)
      && verifier.VerifyTable(tablePos, 10 /*Payload*/, Battlement.FlatBuffers.FixtureGenerated.FlashPayloadVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct FixtureBatchFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static FixtureBatchFailed GetRootAsFixtureBatchFailed(ByteBuffer _bb) { return GetRootAsFixtureBatchFailed(_bb, new FixtureBatchFailed()); }
  public static FixtureBatchFailed GetRootAsFixtureBatchFailed(ByteBuffer _bb, FixtureBatchFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FixtureBatchFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.Generated.Uuid? SessionId { get { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.Generated.Uuid? BatchId { get { int o = __p.__offset(6); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.Generated.Uuid? CommandId { get { int o = __p.__offset(8); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.FixtureGenerated.FixtureError Error { get { int o = __p.__offset(10); return o != 0 ? (Battlement.FlatBuffers.FixtureGenerated.FixtureError)__p.bb.Get(o + __p.bb_pos) : Battlement.FlatBuffers.FixtureGenerated.FixtureError.Rejected; } }
  public string Message { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(12); }

  public static void StartFixtureBatchFailed(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddSessionId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> sessionIdOffset) { builder.AddStruct(0, sessionIdOffset.Value, 0); }
  public static void AddBatchId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> batchIdOffset) { builder.AddStruct(1, batchIdOffset.Value, 0); }
  public static void AddCommandId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> commandIdOffset) { builder.AddStruct(2, commandIdOffset.Value, 0); }
  public static void AddError(FlatBufferBuilder builder, Battlement.FlatBuffers.FixtureGenerated.FixtureError error) { builder.AddByte(3, (byte)error, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(4, messageOffset.Value, 0); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.FixtureBatchFailed> EndFixtureBatchFailed(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // session_id
    builder.Required(o, 6);  // batch_id
    builder.Required(o, 12);  // message
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.FixtureBatchFailed>(o);
  }
}


static public class FixtureBatchFailedVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SessionId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyField(tablePos, 6 /*BatchId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyField(tablePos, 8 /*CommandId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*Error*/, 1 /*Battlement.FlatBuffers.FixtureGenerated.FixtureError*/, 1, false)
      && verifier.VerifyString(tablePos, 12 /*Message*/, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct FixtureOperationFailed : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static FixtureOperationFailed GetRootAsFixtureOperationFailed(ByteBuffer _bb) { return GetRootAsFixtureOperationFailed(_bb, new FixtureOperationFailed()); }
  public static FixtureOperationFailed GetRootAsFixtureOperationFailed(ByteBuffer _bb, FixtureOperationFailed obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FixtureOperationFailed __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.Generated.Uuid? SessionId { get { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.Generated.Uuid? BatchId { get { int o = __p.__offset(6); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.Generated.Uuid? CommandId { get { int o = __p.__offset(8); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.FixtureGenerated.FixtureError Error { get { int o = __p.__offset(10); return o != 0 ? (Battlement.FlatBuffers.FixtureGenerated.FixtureError)__p.bb.Get(o + __p.bb_pos) : Battlement.FlatBuffers.FixtureGenerated.FixtureError.Rejected; } }
  public string Message { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(12); }

  public static void StartFixtureOperationFailed(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddSessionId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> sessionIdOffset) { builder.AddStruct(0, sessionIdOffset.Value, 0); }
  public static void AddBatchId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> batchIdOffset) { builder.AddStruct(1, batchIdOffset.Value, 0); }
  public static void AddCommandId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> commandIdOffset) { builder.AddStruct(2, commandIdOffset.Value, 0); }
  public static void AddError(FlatBufferBuilder builder, Battlement.FlatBuffers.FixtureGenerated.FixtureError error) { builder.AddByte(3, (byte)error, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(4, messageOffset.Value, 0); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.FixtureOperationFailed> EndFixtureOperationFailed(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // session_id
    builder.Required(o, 6);  // batch_id
    builder.Required(o, 8);  // command_id
    builder.Required(o, 12);  // message
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.FixtureOperationFailed>(o);
  }
}


static public class FixtureOperationFailedVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SessionId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyField(tablePos, 6 /*BatchId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyField(tablePos, 8 /*CommandId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyField(tablePos, 10 /*Error*/, 1 /*Battlement.FlatBuffers.FixtureGenerated.FixtureError*/, 1, false)
      && verifier.VerifyString(tablePos, 12 /*Message*/, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct FixtureClientMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static FixtureClientMessage GetRootAsFixtureClientMessage(ByteBuffer _bb) { return GetRootAsFixtureClientMessage(_bb, new FixtureClientMessage()); }
  public static FixtureClientMessage GetRootAsFixtureClientMessage(ByteBuffer _bb, FixtureClientMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FixtureClientMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.FixtureGenerated.FixtureClientBody BodyType { get { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.FixtureGenerated.FixtureClientBody)__p.bb.Get(o + __p.bb_pos) : Battlement.FlatBuffers.FixtureGenerated.FixtureClientBody.NONE; } }
  public TTable? Body<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Battlement.FlatBuffers.Generated.CoreAction BodyAsBattlement_FlatBuffers_Generated_CoreAction() { return Body<Battlement.FlatBuffers.Generated.CoreAction>().Value; }
  public Battlement.FlatBuffers.Generated.BatchFailed BodyAsBattlement_FlatBuffers_Generated_BatchFailed() { return Body<Battlement.FlatBuffers.Generated.BatchFailed>().Value; }
  public Battlement.FlatBuffers.Generated.OperationFailed BodyAsBattlement_FlatBuffers_Generated_OperationFailed() { return Body<Battlement.FlatBuffers.Generated.OperationFailed>().Value; }
  public Battlement.FlatBuffers.FixtureGenerated.FixtureAction BodyAsFixtureAction() { return Body<Battlement.FlatBuffers.FixtureGenerated.FixtureAction>().Value; }
  public Battlement.FlatBuffers.FixtureGenerated.FixtureBatchFailed BodyAsFixtureBatchFailed() { return Body<Battlement.FlatBuffers.FixtureGenerated.FixtureBatchFailed>().Value; }
  public Battlement.FlatBuffers.FixtureGenerated.FixtureOperationFailed BodyAsFixtureOperationFailed() { return Body<Battlement.FlatBuffers.FixtureGenerated.FixtureOperationFailed>().Value; }

  public static Offset<Battlement.FlatBuffers.FixtureGenerated.FixtureClientMessage> CreateFixtureClientMessage(FlatBufferBuilder builder,
      Battlement.FlatBuffers.FixtureGenerated.FixtureClientBody body_type = Battlement.FlatBuffers.FixtureGenerated.FixtureClientBody.NONE,
      int bodyOffset = 0) {
    builder.StartTable(2);
    FixtureClientMessage.AddBody(builder, bodyOffset);
    FixtureClientMessage.AddBodyType(builder, body_type);
    return FixtureClientMessage.EndFixtureClientMessage(builder);
  }

  public static void StartFixtureClientMessage(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddBodyType(FlatBufferBuilder builder, Battlement.FlatBuffers.FixtureGenerated.FixtureClientBody bodyType) { builder.AddByte(0, (byte)bodyType, 0); }
  public static void AddBody(FlatBufferBuilder builder, int bodyOffset) { builder.AddOffset(1, bodyOffset, 0); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.FixtureClientMessage> EndFixtureClientMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 6);  // body
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.FixtureClientMessage>(o);
  }
}


static public class FixtureClientMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*BodyType*/, 1 /*Battlement.FlatBuffers.FixtureGenerated.FixtureClientBody*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Body*/, Battlement.FlatBuffers.FixtureGenerated.FixtureClientBodyVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct CommandEntry : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static CommandEntry GetRootAsCommandEntry(ByteBuffer _bb) { return GetRootAsCommandEntry(_bb, new CommandEntry()); }
  public static CommandEntry GetRootAsCommandEntry(ByteBuffer _bb, CommandEntry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CommandEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.FixtureGenerated.FixtureCommand CommandType { get { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.FixtureGenerated.FixtureCommand)__p.bb.Get(o + __p.bb_pos) : Battlement.FlatBuffers.FixtureGenerated.FixtureCommand.NONE; } }
  public TTable? Command<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Battlement.FlatBuffers.Generated.CoreCommand CommandAsBattlement_FlatBuffers_Generated_CoreCommand() { return Command<Battlement.FlatBuffers.Generated.CoreCommand>().Value; }
  public Battlement.FlatBuffers.FixtureGenerated.FlashCommand CommandAsFlashCommand() { return Command<Battlement.FlatBuffers.FixtureGenerated.FlashCommand>().Value; }

  public static Offset<Battlement.FlatBuffers.FixtureGenerated.CommandEntry> CreateCommandEntry(FlatBufferBuilder builder,
      Battlement.FlatBuffers.FixtureGenerated.FixtureCommand command_type = Battlement.FlatBuffers.FixtureGenerated.FixtureCommand.NONE,
      int commandOffset = 0) {
    builder.StartTable(2);
    CommandEntry.AddCommand(builder, commandOffset);
    CommandEntry.AddCommandType(builder, command_type);
    return CommandEntry.EndCommandEntry(builder);
  }

  public static void StartCommandEntry(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddCommandType(FlatBufferBuilder builder, Battlement.FlatBuffers.FixtureGenerated.FixtureCommand commandType) { builder.AddByte(0, (byte)commandType, 0); }
  public static void AddCommand(FlatBufferBuilder builder, int commandOffset) { builder.AddOffset(1, commandOffset, 0); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.CommandEntry> EndCommandEntry(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 6);  // command
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.CommandEntry>(o);
  }
}


static public class CommandEntryVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*CommandType*/, 1 /*Battlement.FlatBuffers.FixtureGenerated.FixtureCommand*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Command*/, Battlement.FlatBuffers.FixtureGenerated.FixtureCommandVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct ParallelCommandGroup : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static ParallelCommandGroup GetRootAsParallelCommandGroup(ByteBuffer _bb) { return GetRootAsParallelCommandGroup(_bb, new ParallelCommandGroup()); }
  public static ParallelCommandGroup GetRootAsParallelCommandGroup(ByteBuffer _bb, ParallelCommandGroup obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ParallelCommandGroup __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.FixtureGenerated.CommandEntry? Commands(int j) { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.FixtureGenerated.CommandEntry?)(new Battlement.FlatBuffers.FixtureGenerated.CommandEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CommandsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroup> CreateParallelCommandGroup(FlatBufferBuilder builder,
      VectorOffset commandsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ParallelCommandGroup.AddCommands(builder, commandsOffset);
    return ParallelCommandGroup.EndParallelCommandGroup(builder);
  }

  public static void StartParallelCommandGroup(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCommands(FlatBufferBuilder builder, VectorOffset commandsOffset) { builder.AddOffset(0, commandsOffset.Value, 0); }
  public static VectorOffset CreateCommandsVector(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.FixtureGenerated.CommandEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCommandsVectorBlock(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.FixtureGenerated.CommandEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCommandsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Battlement.FlatBuffers.FixtureGenerated.CommandEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCommandsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Battlement.FlatBuffers.FixtureGenerated.CommandEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCommandsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroup> EndParallelCommandGroup(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // commands
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroup>(o);
  }
}


static public class ParallelCommandGroupVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Commands*/, Battlement.FlatBuffers.FixtureGenerated.CommandEntryVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Batch : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Batch GetRootAsBatch(ByteBuffer _bb) { return GetRootAsBatch(_bb, new Batch()); }
  public static Batch GetRootAsBatch(ByteBuffer _bb, Batch obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Batch __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.Generated.Uuid? BatchId { get { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.Generated.Uuid? SessionId { get { int o = __p.__offset(6); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.Generated.Uuid? CausedByActionId { get { int o = __p.__offset(8); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.Generated.BatchStart Start { get { int o = __p.__offset(10); return o != 0 ? (Battlement.FlatBuffers.Generated.BatchStart)__p.bb.Get(o + __p.bb_pos) : Battlement.FlatBuffers.Generated.BatchStart.Now; } }
  public ulong? WorkScope { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong?)null; } }
  public ulong? CancelScope { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong?)null; } }
  public Battlement.FlatBuffers.Generated.PresentationControl? PresentationControl { get { int o = __p.__offset(16); return o != 0 ? (Battlement.FlatBuffers.Generated.PresentationControl?)(new Battlement.FlatBuffers.Generated.PresentationControl()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroup? Groups(int j) { int o = __p.__offset(18); return o != 0 ? (Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroup?)(new Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroup()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int GroupsLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static void StartBatch(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddBatchId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> batchIdOffset) { builder.AddStruct(0, batchIdOffset.Value, 0); }
  public static void AddSessionId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> sessionIdOffset) { builder.AddStruct(1, sessionIdOffset.Value, 0); }
  public static void AddCausedByActionId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> causedByActionIdOffset) { builder.AddStruct(2, causedByActionIdOffset.Value, 0); }
  public static void AddStart(FlatBufferBuilder builder, Battlement.FlatBuffers.Generated.BatchStart start) { builder.AddByte(3, (byte)start, 0); }
  public static void AddWorkScope(FlatBufferBuilder builder, ulong? workScope) { builder.AddUlong(4, workScope); }
  public static void AddCancelScope(FlatBufferBuilder builder, ulong? cancelScope) { builder.AddUlong(5, cancelScope); }
  public static void AddPresentationControl(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.PresentationControl> presentationControlOffset) { builder.AddOffset(6, presentationControlOffset.Value, 0); }
  public static void AddGroups(FlatBufferBuilder builder, VectorOffset groupsOffset) { builder.AddOffset(7, groupsOffset.Value, 0); }
  public static VectorOffset CreateGroupsVector(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroup>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateGroupsVectorBlock(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroup>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateGroupsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroup>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateGroupsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroup>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartGroupsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.Batch> EndBatch(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // batch_id
    builder.Required(o, 6);  // session_id
    builder.Required(o, 18);  // groups
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.Batch>(o);
  }
}


static public class BatchVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*BatchId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyField(tablePos, 6 /*SessionId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyField(tablePos, 8 /*CausedByActionId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, false)
      && verifier.VerifyField(tablePos, 10 /*Start*/, 1 /*Battlement.FlatBuffers.Generated.BatchStart*/, 1, false)
      && verifier.VerifyField(tablePos, 12 /*WorkScope*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 14 /*CancelScope*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTable(tablePos, 16 /*PresentationControl*/, Battlement.FlatBuffers.Generated.PresentationControlVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 18 /*Groups*/, Battlement.FlatBuffers.FixtureGenerated.ParallelCommandGroupVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct ResponseMessageEntry : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static ResponseMessageEntry GetRootAsResponseMessageEntry(ByteBuffer _bb) { return GetRootAsResponseMessageEntry(_bb, new ResponseMessageEntry()); }
  public static ResponseMessageEntry GetRootAsResponseMessageEntry(ByteBuffer _bb, ResponseMessageEntry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ResponseMessageEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.FixtureGenerated.ResponseMessage MessageType { get { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.FixtureGenerated.ResponseMessage)__p.bb.Get(o + __p.bb_pos) : Battlement.FlatBuffers.FixtureGenerated.ResponseMessage.NONE; } }
  public TTable? Message<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public Battlement.FlatBuffers.Generated.Snapshot MessageAsBattlement_FlatBuffers_Generated_Snapshot() { return Message<Battlement.FlatBuffers.Generated.Snapshot>().Value; }
  public Battlement.FlatBuffers.FixtureGenerated.Batch MessageAsBatch() { return Message<Battlement.FlatBuffers.FixtureGenerated.Batch>().Value; }

  public static Offset<Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntry> CreateResponseMessageEntry(FlatBufferBuilder builder,
      Battlement.FlatBuffers.FixtureGenerated.ResponseMessage message_type = Battlement.FlatBuffers.FixtureGenerated.ResponseMessage.NONE,
      int messageOffset = 0) {
    builder.StartTable(2);
    ResponseMessageEntry.AddMessage(builder, messageOffset);
    ResponseMessageEntry.AddMessageType(builder, message_type);
    return ResponseMessageEntry.EndResponseMessageEntry(builder);
  }

  public static void StartResponseMessageEntry(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddMessageType(FlatBufferBuilder builder, Battlement.FlatBuffers.FixtureGenerated.ResponseMessage messageType) { builder.AddByte(0, (byte)messageType, 0); }
  public static void AddMessage(FlatBufferBuilder builder, int messageOffset) { builder.AddOffset(1, messageOffset, 0); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntry> EndResponseMessageEntry(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 6);  // message
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntry>(o);
  }
}


static public class ResponseMessageEntryVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*MessageType*/, 1 /*Battlement.FlatBuffers.FixtureGenerated.ResponseMessage*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Message*/, Battlement.FlatBuffers.FixtureGenerated.ResponseMessageVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Response : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_12_19(); }
  public static Response GetRootAsResponse(ByteBuffer _bb) { return GetRootAsResponse(_bb, new Response()); }
  public static Response GetRootAsResponse(ByteBuffer _bb, Response obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool ResponseBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "BTRS"); }
  public static bool VerifyResponse(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("BTRS", false, ResponseVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Response __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Battlement.FlatBuffers.Generated.Uuid? SessionId { get { int o = __p.__offset(4); return o != 0 ? (Battlement.FlatBuffers.Generated.Uuid?)(new Battlement.FlatBuffers.Generated.Uuid()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntry? Messages(int j) { int o = __p.__offset(6); return o != 0 ? (Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntry?)(new Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MessagesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static void StartResponse(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSessionId(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.Generated.Uuid> sessionIdOffset) { builder.AddStruct(0, sessionIdOffset.Value, 0); }
  public static void AddMessages(FlatBufferBuilder builder, VectorOffset messagesOffset) { builder.AddOffset(1, messagesOffset.Value, 0); }
  public static VectorOffset CreateMessagesVector(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMessagesVectorBlock(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMessagesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntry>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMessagesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntry>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMessagesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Battlement.FlatBuffers.FixtureGenerated.Response> EndResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // session_id
    builder.Required(o, 6);  // messages
    return new Offset<Battlement.FlatBuffers.FixtureGenerated.Response>(o);
  }
  public static void FinishResponseBuffer(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.FixtureGenerated.Response> offset) { builder.Finish(offset.Value, "BTRS"); }
  public static void FinishSizePrefixedResponseBuffer(FlatBufferBuilder builder, Offset<Battlement.FlatBuffers.FixtureGenerated.Response> offset) { builder.FinishSizePrefixed(offset.Value, "BTRS"); }
}


static public class ResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SessionId*/, 16 /*Battlement.FlatBuffers.Generated.Uuid*/, 1, true)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Messages*/, Battlement.FlatBuffers.FixtureGenerated.ResponseMessageEntryVerify.Verify, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
