version = 1

[[states]]
key = "screen.menu"
screen = "chess"

[[states]]
key = "screen.settings"
screen = "chess"

[[states]]
key = "board.new-game"
screen = "chess"

[[states]]
key = "screen.returned-menu"
screen = "chess"

[[states]]
key = "terminal.computer-win"
screen = "chess"

[[states]]
key = "board.resumed"
screen = "chess"
