// @generated by `cargo battlement generate`; do not edit.

pub mod ui {
    use battlement::SceneAddress;

    /// Addressable key `ui/content` (UnityEditor.SceneAsset) from `Assets/Scenes/Content.unity` in group `Battlement UI Sample`.
    pub const CONTENT: SceneAddress = SceneAddress::from_static("ui/content");

    pub mod assets {
        use battlement::{
            RenderTextureAddress, SpriteAddress, TextureAddress, UiFontAddress, UnityFontAddress,
            VectorImageAddress,
        };

        /// Addressable key `ui/assets/cursor` (UnityEngine.Texture2D) from `Assets/Original/Signal Cursor.png` in group `Battlement UI Sample`.
        pub const CURSOR: TextureAddress = TextureAddress::from_static("ui/assets/cursor");
        /// Addressable key `ui/assets/render-texture` (UnityEngine.RenderTexture) from `Assets/Original/Signal Render Texture.renderTexture` in group `Battlement UI Sample`.
        pub const RENDER_TEXTURE: RenderTextureAddress =
            RenderTextureAddress::from_static("ui/assets/render-texture");
        /// Addressable key `ui/assets/sprite` (UnityEngine.Texture2D) from `Assets/Original/Signal Sprite.png` in group `Battlement UI Sample`.
        pub const SPRITE: SpriteAddress = SpriteAddress::from_static("ui/assets/sprite");
        /// Addressable key `ui/assets/texture` (UnityEngine.Texture2D) from `Assets/Original/Signal Texture.png` in group `Battlement UI Sample`.
        pub const TEXTURE: TextureAddress = TextureAddress::from_static("ui/assets/texture");
        /// Addressable key `ui/assets/ui-font` (UnityEngine.TextCore.Text.FontAsset) from `Assets/Original/Command UI Font.asset` in group `Battlement UI Sample`.
        pub const UI_FONT: UiFontAddress = UiFontAddress::from_static("ui/assets/ui-font");
        /// Addressable key `ui/assets/unity-font` (UnityEngine.Font) from `Assets/Original/Command Mono.ttf` in group `Battlement UI Sample`.
        pub const UNITY_FONT: UnityFontAddress =
            UnityFontAddress::from_static("ui/assets/unity-font");
        /// Addressable key `ui/assets/vector` (UnityEngine.UIElements.VectorImage) from `Assets/Original/Signal Vector.svg` in group `Battlement UI Sample`.
        pub const VECTOR: VectorImageAddress = VectorImageAddress::from_static("ui/assets/vector");
    }
}

use battlement::PreparedAsset;

/// Every generated address that maps directly to a prepared runtime asset.
pub const ASSET_CATALOG: &[PreparedAsset] = &[
    PreparedAsset::Texture(ui::assets::CURSOR),
    PreparedAsset::RenderTexture(ui::assets::RENDER_TEXTURE),
    PreparedAsset::Sprite(ui::assets::SPRITE),
    PreparedAsset::Texture(ui::assets::TEXTURE),
    PreparedAsset::UiFont(ui::assets::UI_FONT),
    PreparedAsset::UnityFont(ui::assets::UNITY_FONT),
    PreparedAsset::VectorImage(ui::assets::VECTOR),
    PreparedAsset::Scene(ui::CONTENT),
];
