[package]
name = "battlement-chess-ui-rules"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "battlement_rules"
crate-type = ["cdylib", "rlib"]

[dependencies]
battlement = { path = "../../../crates/battlement" }
reactant = { path = "../../../crates/reactant" }
serde = { version = "1.0.228", features = ["derive"] }
trox = "0.2.1"

[dev-dependencies]
battlement-fake = { path = "../../../crates/battlement-fake" }
reactant-testing = { path = "../../../crates/reactant-testing", default-features = false }
syn = { version = "2.0.119", features = ["full", "visit"] }

[workspace]
