use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{Context, Result, bail};
use serde::Deserialize;
use tempfile::Builder;

const MARKER: &str = "// @generated by `cargo battlement generate`; do not edit.\n";

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd)]
enum AssetKind {
    Scene,
    Prefab,
    Material,
    Texture,
    Sprite,
    VectorImage,
    RenderTexture,
    AudioClip,
    Font,
    UiFont,
    UnityFont,
    Untyped,
}

impl AssetKind {
    fn rust_type(self) -> &'static str {
        match self {
            Self::Scene => "SceneAddress",
            Self::Prefab => "PrefabAddress",
            Self::Material => "MaterialAddress",
            Self::Texture => "TextureAddress",
            Self::Sprite => "SpriteAddress",
            Self::VectorImage => "VectorImageAddress",
            Self::RenderTexture => "RenderTextureAddress",
            Self::AudioClip => "AudioClipAddress",
            Self::Font => "FontAddress",
            Self::UiFont => "UiFontAddress",
            Self::UnityFont => "UnityFontAddress",
            Self::Untyped => "UntypedAssetAddress",
        }
    }

    fn prepared_variant(self) -> Option<&'static str> {
        match self {
            Self::Scene => Some("Scene"),
            Self::Prefab => Some("Prefab"),
            Self::Material => Some("Material"),
            Self::Texture => Some("Texture"),
            Self::Sprite => Some("Sprite"),
            Self::VectorImage => Some("VectorImage"),
            Self::RenderTexture => Some("RenderTexture"),
            Self::AudioClip => Some("AudioClip"),
            Self::Font => Some("Font"),
            Self::UiFont => Some("UiFont"),
            Self::UnityFont => Some("UnityFont"),
            Self::Untyped => None,
        }
    }
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct ExportEntry {
    address: String,
    kind: AssetKind,
    group: String,
    asset_path: String,
    unity_type: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct ExportFile {
    entries: Vec<ExportEntry>,
}

#[derive(Default)]
struct Module {
    constants: BTreeMap<String, ExportEntry>,
    children: BTreeMap<String, ChildModule>,
}

struct ChildModule {
    declaration: String,
    source_segment: String,
    module: Module,
}

pub(crate) fn run(project: Option<&Path>, output: Option<&Path>, check: bool) -> Result<()> {
    let project = self::project(project)?;
    let output = match output {
        Some(path) if path.is_absolute() => path.to_owned(),
        Some(path) => env::current_dir()?.join(path),
        None => project.join("rules/src/assets.rs"),
    };
    let mut entries = self::export(&project)?;
    entries.sort_by(|left, right| left.address.cmp(&right.address));
    let count = entries.len();
    let module = self::module(entries.clone())?;
    let parent = output
        .parent()
        .context("generated module path has no parent")?;
    fs::create_dir_all(parent).with_context(|| format!("failed to create {}", parent.display()))?;
    let staging = Builder::new()
        .prefix(".battlement-addresses-")
        .tempfile_in(parent)?;
    fs::write(staging.path(), self::render(&module, &entries))?;
    let formatting = Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(staging.path())
        .status()
        .context("failed to launch rustfmt for the generated Addressables module")?;
    if !formatting.success() {
        bail!("rustfmt rejected the generated Addressables module");
    }

    if check {
        if !self::same_file(&output, staging.path())? {
            bail!(
                "generated Addressables module is stale at {}; run `cargo battlement generate {}`",
                output.display(),
                project.display()
            );
        }
        println!("Checked {} ({count} addresses)", output.display());
        return Ok(());
    }
    if self::same_file(&output, staging.path())? {
        println!(
            "Generated {} ({count} addresses, unchanged)",
            output.display()
        );
        return Ok(());
    }
    if output.exists() {
        let existing = fs::read_to_string(&output).unwrap_or_default();
        if !existing.starts_with(MARKER) {
            bail!("refusing to replace unmarked file {}", output.display());
        }
    }
    staging
        .persist(&output)
        .map_err(|error| error.error)
        .context("failed to install generated module")?;
    println!("Generated {} ({count} addresses)", output.display());
    Ok(())
}

fn project(explicit: Option<&Path>) -> Result<PathBuf> {
    if let Some(path) = explicit {
        return self::validate_project(path);
    }
    let current = env::current_dir()?;
    for ancestor in current.ancestors() {
        if self::is_project(ancestor) {
            return Ok(ancestor.to_owned());
        }
    }
    bail!(
        "could not find a Unity project from {}; pass its path to `cargo battlement generate`",
        current.display()
    )
}

fn validate_project(path: &Path) -> Result<PathBuf> {
    let path = fs::canonicalize(path)
        .with_context(|| format!("failed to open Unity project {}", path.display()))?;
    if !self::is_project(&path) {
        bail!("{} is not a Unity project", path.display());
    }
    Ok(path)
}

fn is_project(path: &Path) -> bool {
    path.join("Assets").is_dir() && path.join("ProjectSettings/ProjectVersion.txt").is_file()
}

fn export(project: &Path) -> Result<Vec<ExportEntry>> {
    let temporary = Builder::new().prefix("battlement-addresses-").tempdir()?;
    let export_path = temporary.path().join("addresses.json");
    let log_path = temporary.path().join("unity.log");
    let status = Command::new(self::unity_editor(project)?)
        .args([
            "-batchmode",
            "-nographics",
            "--burst-disable-compilation",
            "-quit",
            "-projectPath",
        ])
        .arg(project)
        .args([
            "-executeMethod",
            "Battlement.Editor.BattlementAddressExport.Export",
            "-logFile",
        ])
        .arg(&log_path)
        .env("BATTLEMENT_ADDRESS_EXPORT_PATH", &export_path)
        .current_dir(project)
        .status()
        .context("failed to launch Unity for Addressables export")?;
    if !status.success() {
        let log = fs::read_to_string(&log_path).unwrap_or_default();
        let tail = log.lines().rev().take(60).collect::<Vec<_>>();
        bail!(
            "Unity Addressables export failed with status {status}:\n{}",
            tail.into_iter().rev().collect::<Vec<_>>().join("\n")
        );
    }
    let data =
        fs::read(&export_path).context("Unity exited without writing its Addressables export")?;
    let export: ExportFile =
        serde_json::from_slice(&data).context("Unity wrote an invalid Addressables export")?;
    Ok(export.entries)
}

fn unity_editor(project: &Path) -> Result<PathBuf> {
    if let Some(configured) = env::var_os("UNITY_EDITOR") {
        return Ok(configured.into());
    }
    let version = fs::read_to_string(project.join("ProjectSettings/ProjectVersion.txt"))?
        .lines()
        .find_map(|line| line.strip_prefix("m_EditorVersion: "))
        .context("ProjectVersion.txt has no Unity editor version")?
        .to_owned();
    #[cfg(target_os = "macos")]
    let editor = format!("/Applications/Unity/Hub/Editor/{version}/Unity.app/Contents/MacOS/Unity");
    #[cfg(target_os = "linux")]
    let editor = format!(
        "{}/Unity/Hub/Editor/{version}/Editor/Unity",
        env::var("HOME")?
    );
    #[cfg(target_os = "windows")]
    let editor = format!(r"C:\Program Files\Unity\Hub\Editor\{version}\Editor\Unity.exe");
    #[cfg(not(any(target_os = "macos", target_os = "linux", target_os = "windows")))]
    bail!("set UNITY_EDITOR on this operating system");
    Ok(PathBuf::from(editor))
}

fn module(mut entries: Vec<ExportEntry>) -> Result<Module> {
    entries.sort_by(|left, right| left.address.cmp(&right.address));
    let mut seen = BTreeSet::new();
    let mut root = Module::default();
    for entry in entries {
        if !seen.insert(entry.address.clone()) {
            bail!(
                "Addressables key {:?} is declared more than once",
                entry.address
            );
        }
        let segments = entry.address.split('/').collect::<Vec<_>>();
        if segments.iter().any(|segment| segment.is_empty()) {
            bail!(
                "Addressables key {:?} contains an empty path segment",
                entry.address
            );
        }
        let mut current = &mut root;
        for segment in &segments[..segments.len() - 1] {
            let (file_name, declaration) = self::module_identifier(segment);
            let child = current
                .children
                .entry(file_name)
                .or_insert_with(|| ChildModule {
                    declaration,
                    source_segment: (*segment).to_owned(),
                    module: Module::default(),
                });
            if child.source_segment != *segment {
                bail!(
                    "address segments {:?} and {:?} map to the same Rust module {:?}",
                    child.source_segment,
                    segment,
                    child.declaration
                );
            }
            current = &mut child.module;
        }
        let name = self::constant_identifier(segments[segments.len() - 1]);
        if let Some(previous) = current.constants.insert(name.clone(), entry.clone()) {
            bail!(
                "Addressables keys {:?} and {:?} map to the same Rust constant {name}",
                previous.address,
                entry.address
            );
        }
    }
    Ok(root)
}

fn module_identifier(value: &str) -> (String, String) {
    let mut identifier = self::sanitize(value, false);
    let file_name = identifier.clone();
    if ["crate", "self", "super"].contains(&identifier.as_str()) {
        identifier.insert(0, '_');
        return (identifier.clone(), identifier);
    }
    let declaration = if self::rust_keyword(&identifier) {
        format!("r#{identifier}")
    } else {
        identifier
    };
    (file_name, declaration)
}

fn constant_identifier(value: &str) -> String {
    self::sanitize(value, true)
}

fn sanitize(value: &str, uppercase: bool) -> String {
    let mut result = String::new();
    let mut previous_underscore = false;
    for character in value.chars() {
        if character.is_ascii_alphanumeric() || character == '_' {
            let character = if uppercase {
                character.to_ascii_uppercase()
            } else {
                character.to_ascii_lowercase()
            };
            result.push(character);
            previous_underscore = character == '_';
        } else if character.is_ascii() {
            if !previous_underscore {
                result.push('_');
                previous_underscore = true;
            }
        } else {
            result.push_str(&format!("_u{:x}_", character as u32));
            previous_underscore = true;
        }
    }
    while result.ends_with('_') && result.len() > 1 {
        result.pop();
    }
    if result.is_empty() {
        result.push('_');
    }
    if result.as_bytes()[0].is_ascii_digit() {
        result.insert(0, '_');
    }
    result
}

fn rust_keyword(value: &str) -> bool {
    matches!(
        value,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
    )
}

fn render(module: &Module, entries: &[ExportEntry]) -> String {
    let mut source = String::from(MARKER);
    source.push('\n');
    self::write_module(&mut source, module, 0);
    source.push_str("\nuse battlement::PreparedAsset;\n\n");
    source
        .push_str("/// Every generated address that maps directly to a prepared runtime asset.\n");
    source.push_str("pub const ASSET_CATALOG: &[PreparedAsset] = &[\n");
    for entry in entries {
        let Some(variant) = entry.kind.prepared_variant() else {
            continue;
        };
        source.push_str(&format!(
            "    PreparedAsset::{variant}({}),\n",
            self::constant_path(&entry.address)
        ));
    }
    source.push_str("];\n");
    source
}

fn constant_path(address: &str) -> String {
    let segments = address.split('/').collect::<Vec<_>>();
    let mut path = segments[..segments.len() - 1]
        .iter()
        .map(|segment| self::module_identifier(segment).1)
        .collect::<Vec<_>>();
    path.push(self::constant_identifier(segments[segments.len() - 1]));
    path.join("::")
}

fn write_module(source: &mut String, module: &Module, depth: usize) {
    let indentation = "    ".repeat(depth);
    let types = module
        .constants
        .values()
        .map(|entry| entry.kind.rust_type())
        .collect::<BTreeSet<_>>();
    if !types.is_empty() {
        let types = types.into_iter().collect::<Vec<_>>();
        if types.len() == 1 {
            source.push_str(&format!("{indentation}use battlement::{};\n\n", types[0]));
        } else {
            source.push_str(&format!(
                "{indentation}use battlement::{{{}}};\n\n",
                types.join(", ")
            ));
        }
    }
    for entry in module.constants.values() {
        let name = self::constant_identifier(
            entry
                .address
                .rsplit('/')
                .next()
                .expect("an address has a leaf"),
        );
        let rust_type = entry.kind.rust_type();
        source.push_str(&format!(
            "{indentation}/// Addressable key `{}` ({}) from `{}` in group `{}`.\n",
            entry.address, entry.unity_type, entry.asset_path, entry.group
        ));
        let declaration = format!(
            "{indentation}pub const {name}: {rust_type} = {rust_type}::from_static({:?});\n",
            entry.address
        );
        if declaration.trim_end().chars().count() <= 100 {
            source.push_str(&declaration);
        } else {
            source.push_str(&format!(
                "{indentation}pub const {name}: {rust_type} =\n{indentation}    {rust_type}::from_static({:?});\n",
                entry.address
            ));
        }
    }
    if !module.constants.is_empty() && !module.children.is_empty() {
        source.push('\n');
    }
    for (index, child) in module.children.values().enumerate() {
        source.push_str(&format!("{indentation}pub mod {} {{\n", child.declaration));
        self::write_module(source, &child.module, depth + 1);
        source.push_str(&format!("{indentation}}}\n"));
        if index + 1 != module.children.len() {
            source.push('\n');
        }
    }
}

fn same_file(left: &Path, right: &Path) -> Result<bool> {
    if !left.is_file() {
        return Ok(false);
    }
    Ok(fs::read(left)? == fs::read(right)?)
}
