[package]
name = "battlement-reactant"
version = "0.1.0"
description = "Declarative Battlement UI runtime"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
battlement = { path = "../battlement" }
battlement-reactant-asset-macros = { path = "../battlement-reactant-asset-macros" }
inventory.workspace = true
serde_json.workspace = true

[dev-dependencies]
battlement-fake = { path = "../battlement-fake" }
battlement-native = { path = "../battlement-native" }
uuid.workspace = true
