[package]
name = "battlement-reactant-asset-macros"
version = "0.1.0"
description = "Procedural macros for Reactant generated assets"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
battlement-reactant-asset-syntax.workspace = true
proc-macro2 = "1.0.107"
quote = "1.0.42"
