#!/usr/bin/env python3

"""Verify staged-input freezing, generator selection, and convergence."""

from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPOSITORY_ROOT / "scripts"))
SPEC = importlib.util.spec_from_file_location(
    "prepare_validation", REPOSITORY_ROOT / "scripts/prepare_validation.py",
)
assert SPEC and SPEC.loader
module = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(module)
GENERATED_MARKER = "// @generated by `cargo battlement generate`; do not edit.\n"


def main() -> None:
    with tempfile.TemporaryDirectory(prefix="battlement-preparation-test.") as temporary:
        root = Path(temporary)
        create_repository(root)
        output = root / "evidence/manifest.json"
        patch = root / "evidence/generated.patch"
        generated = root / "samples/fixture/rules/src/assets.rs"
        calls = []

        def stable_runner(command: list[str], *, cwd: Path) -> None:
            calls.append(command)
            if "--check" not in command and "// updated" not in generated.read_text():
                generated.write_text(GENERATED_MARKER + "// updated\n")

        old_log_root = os.environ.get("BATTLEMENT_LOG_ROOT")
        os.environ["BATTLEMENT_LOG_ROOT"] = str(root / "logs")
        try:
            manifest = module.prepare(
                root, "generate", None, output, patch, runner=stable_runner,
            )
        finally:
            if old_log_root is None:
                os.environ.pop("BATTLEMENT_LOG_ROOT", None)
            else:
                os.environ["BATTLEMENT_LOG_ROOT"] = old_log_root
        assert len(calls) == 2, calls
        assert manifest["selected_producers"] == [
            {"sample": "fixture", "producer": "addressables"},
        ]
        assert json.loads(output.read_text())["source_manifest_sha256"]
        assert b"generated" in patch.read_bytes()
        assert subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=root).returncode == 1

        generated.write_text(GENERATED_MARKER + "// original\n")

        def unstable_runner(_command: list[str], *, cwd: Path) -> None:
            current = generated.read_text()
            suffix = "// alternating-a\n" if "alternating-b" in current else "// alternating-b\n"
            generated.write_text(GENERATED_MARKER + suffix)

        try:
            module.prepare(
                root, "generate", ["fixture"], root / "unstable.json",
                root / "unstable.patch", runner=unstable_runner,
            )
        except RuntimeError as error:
            assert "did not converge" in str(error)
        else:
            raise AssertionError("non-converging producer was accepted")

        source = root / "samples/fixture/rules/src/lib.rs"
        source.write_text("pub fn changed() {}\n")
        try:
            module.prepare(
                root, "check", ["fixture"], root / "conflict.json",
                root / "conflict.patch", runner=stable_runner,
            )
        except RuntimeError as error:
            assert "conflict with the staged snapshot" in str(error)
        else:
            raise AssertionError("unstaged generator input was accepted")
    print("Validation preparation tests passed.")


def create_repository(root: Path) -> None:
    files = {
        "Cargo.toml": "[workspace]\n",
        "Cargo.lock": "version = 4\n",
        "rust-toolchain.toml": "[toolchain]\nchannel = 'stable'\n",
        "scripts/prepare_validation.py": "# fixture\n",
        "crates/battlement-cli/src/generate.rs": "// generator\n",
        "crates/battlement-cli/src/reactant_assets.rs": "// generator\n",
        "crates/battlement-reactant/src/asset_generator/mod.rs": "// generator\n",
        "samples/fixture/sample.toml": "application = 'Fixture.app'\nscene = 'Assets/Main.unity'\n",
        "samples/fixture/ditto.toml": "[[scenarios]]\nname = 'smoke'\nsteps = []\n",
        "samples/fixture/rules/src/lib.rs": "pub fn fixture() {}\n",
        "samples/fixture/rules/src/assets.rs": GENERATED_MARKER + "// original\n",
        "samples/fixture/Assets/AddressableAssetsData/settings": "original\n",
    }
    for relative, contents in files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents)
    subprocess.run(["git", "init", "--quiet"], cwd=root, check=True)
    subprocess.run(["git", "add", "."], cwd=root, check=True)
    subprocess.run(
        ["git", "-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid",
         "commit", "--quiet", "-m", "fixture"], cwd=root, check=True,
    )
    changed = root / "samples/fixture/Assets/AddressableAssetsData/settings"
    changed.write_text("changed\n")
    subprocess.run(["git", "add", str(changed)], cwd=root, check=True)


if __name__ == "__main__":
    main()
