#!/usr/bin/env python3
"""Freeze staged validation inputs and converge only affected generated outputs."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import platform
import subprocess
import sys
import tempfile
import tomllib
import uuid

import operation_log


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
GENERATOR_INPUTS = (
    "crates/battlement-cli/src/generate.rs",
    "crates/battlement-cli/src/reactant_assets.rs",
    "crates/battlement-reactant/src/asset_generator",
)


def changed_paths(repository: Path) -> list[str]:
    """Return the exact candidate or staged change set used for preparation."""
    revision = git(repository, "rev-parse", "HEAD")
    if os.environ.get("TOLLGATE_TESTED_OID") == revision:
        base = f"{revision}^"
        return nul_paths(repository, "diff", "--name-only", "--no-renames", "-z", base, revision, "--")
    staged = nul_paths(repository, "diff", "--cached", "--name-only", "--no-renames", "-z", "--")
    if staged:
        return staged
    try:
        base = git(repository, "merge-base", "HEAD", "release")
    except subprocess.CalledProcessError:
        base = f"{revision}^"
    return nul_paths(repository, "diff", "--name-only", "--no-renames", "-z", base, revision, "--")


def sample_names(repository: Path) -> list[str]:
    return sorted(path.parent.name for path in (repository / "samples").glob("*/sample.toml"))


def producers_for(
    repository: Path, paths: list[str], explicit_samples: list[str] | None = None,
) -> list[tuple[str, str]]:
    """Select generators from authoritative outputs, declarations, and changed inputs."""
    names = sample_names(repository)
    requested = set(explicit_samples or [])
    unknown = requested - set(names)
    if unknown:
        raise RuntimeError("Unknown samples: " + ", ".join(sorted(unknown)))
    all_generators = any(
        path == declared or path.startswith(declared.rstrip("/") + "/")
        for path in paths for declared in GENERATOR_INPUTS
    )
    selected: list[tuple[str, str]] = []
    for sample in names:
        root = repository / "samples" / sample
        generated_module = root / "rules/src/assets.rs"
        addressable_owned = (
            generated_module.is_file()
            and generated_module.read_text(errors="replace").startswith(
                "// @generated by `cargo battlement generate`; do not edit."
            )
        )
        sources = list((root / "rules/src").glob("**/*.rs"))
        has_reactant = any("asset_generator::generate" in path.read_text(errors="replace") for path in sources)
        sample_paths = [path for path in paths if path.startswith(f"samples/{sample}/")]
        explicit = sample in requested
        addressable_changed = any(
            "/Assets/AddressableAssetsData/" in f"/{path}"
            or path.endswith("/rules/src/assets.rs")
            or path.endswith("/sample.toml")
            for path in sample_paths
        )
        reactant_changed = any(
            path.startswith(f"samples/{sample}/Assets/Original/")
            or (
                path.startswith(f"samples/{sample}/rules/src/")
                and (repository / path).is_file()
                and "asset_generator::generate" in (repository / path).read_text(errors="replace")
            )
            for path in sample_paths
        )
        if addressable_owned and (explicit or all_generators or addressable_changed):
            selected.append((sample, "addressables"))
        if has_reactant and (explicit or all_generators or reactant_changed):
            selected.append((sample, "reactant-assets"))
    return sorted(selected, key=lambda item: (item[1] != "reactant-assets", item[0]))


def validate_metadata(repository: Path, samples: list[str]) -> None:
    """Reject malformed sample and scenario inventories before build capacity is used."""
    for sample in samples:
        root = repository / "samples" / sample
        manifest = tomllib.loads((root / "sample.toml").read_text())
        if not isinstance(manifest.get("application"), str) or not isinstance(manifest.get("scene"), str):
            raise RuntimeError(f"{sample}: sample.toml requires application and scene")
        suite_path = root / "ditto.toml"
        if not suite_path.is_file():
            continue
        suite = tomllib.loads(suite_path.read_text())
        scenarios = suite.get("scenarios", [])
        names = [scenario.get("name") for scenario in scenarios]
        if any(not isinstance(name, str) or not name.strip() for name in names):
            raise RuntimeError(f"{sample}: every Ditto scenario requires a name")
        if len(names) != len(set(names)):
            raise RuntimeError(f"{sample}: Ditto scenario names must be unique")


def relevant_inputs(repository: Path, producers: list[tuple[str, str]]) -> list[str]:
    paths = {"Cargo.toml", "Cargo.lock", "rust-toolchain.toml", "scripts/prepare_validation.py"}
    for sample, producer in producers:
        paths.update({f"samples/{sample}/sample.toml", f"samples/{sample}/rules"})
        if producer == "addressables":
            paths.add(f":(exclude)samples/{sample}/rules/src/assets.rs")
            paths.add(f"samples/{sample}/Assets/AddressableAssetsData")
            paths.add("crates/battlement-cli/src/generate.rs")
        else:
            paths.add(f"samples/{sample}/Assets/Original")
            paths.add("crates/battlement-cli/src/reactant_assets.rs")
            paths.add("crates/battlement-reactant/src/asset_generator")
    return sorted(paths)


def reject_unstaged_inputs(repository: Path, paths: list[str]) -> None:
    if not paths:
        return
    status = subprocess.run(
        ["git", "status", "--porcelain=v1", "-z", "--untracked-files=all", "--no-renames"],
        cwd=repository, check=True, capture_output=True,
    ).stdout
    conflicts = []
    for record in status.split(b"\0"):
        if not record:
            continue
        relative = record[3:].decode(errors="replace")
        if selected_path(relative, paths) and (
            record.startswith(b"??") or len(record) < 2 or record[1:2] != b" "
        ):
            conflicts.append(relative)
    if conflicts:
        raise RuntimeError(
            "Validation inputs conflict with the staged snapshot:\n" + "\n".join(sorted(conflicts))
        )


def run_producer(
    repository: Path, producer: tuple[str, str], check: bool,
    runner=operation_log.run,
) -> None:
    sample, kind = producer
    command = ["cargo", "run", "--quiet", "-p", "battlement-cli", "--"]
    if kind == "reactant-assets":
        command.extend(["reactant", "assets", "check" if check else "generate", "--project", f"samples/{sample}"])
    else:
        command.extend(["generate", f"samples/{sample}"])
        if check:
            command.append("--check")
    runner(command, cwd=repository)


def generated_paths(producers: list[tuple[str, str]]) -> list[str]:
    paths = []
    for sample, kind in producers:
        if kind == "addressables":
            paths.append(f"samples/{sample}/rules/src/assets.rs")
        else:
            paths.extend([
                f"samples/{sample}/Assets/Generated",
                f"samples/{sample}/Assets/Generated.meta",
            ])
    return sorted(set(paths))


def tree_snapshot(repository: Path, paths: list[str]) -> dict[str, str]:
    result = {}
    for relative in paths:
        path = repository / relative
        entries = [path] if path.is_file() else sorted(path.rglob("*")) if path.is_dir() else []
        for entry in entries:
            if entry.is_file() and not entry.is_symlink():
                result[entry.relative_to(repository).as_posix()] = file_digest(entry)
    return result


def input_digest(repository: Path, paths: list[str]) -> str:
    tracked = nul_paths(repository, "ls-files", "-z")
    digest = hashlib.sha256()
    for relative in sorted(path for path in tracked if selected_path(path, paths)):
        encoded = relative.encode()
        digest.update(len(encoded).to_bytes(8, "big"))
        digest.update(encoded)
        digest.update(bytes.fromhex(file_digest(repository / relative)))
    return digest.hexdigest()


def selected_path(relative: str, pathspecs: list[str]) -> bool:
    exclusions = [path.removeprefix(":(exclude)") for path in pathspecs if path.startswith(":(exclude)")]
    positives = [path for path in pathspecs if not path.startswith(":(exclude)")]
    included = any(relative == path or relative.startswith(path.rstrip("/") + "/") for path in positives)
    excluded = any(relative == path or relative.startswith(path.rstrip("/") + "/") for path in exclusions)
    return included and not excluded


def prepare(
    repository: Path, mode: str, explicit_samples: list[str] | None,
    output: Path, diff_output: Path, runner=operation_log.run,
) -> dict:
    paths = changed_paths(repository)
    producers = producers_for(repository, paths, explicit_samples)
    selected_samples = sorted(set(explicit_samples or []) | {sample for sample, _ in producers})
    validate_metadata(repository, selected_samples or sample_names(repository))
    inputs = relevant_inputs(repository, producers)
    reject_unstaged_inputs(repository, inputs)
    frozen = input_digest(repository, inputs)
    before_index = git(repository, "write-tree")
    outputs = generated_paths(producers)
    with operation_log.Operation(
        repository, "Validation preparation",
        metadata={"mode": mode, "selected_producers": producers},
    ) as operation:
        operation.event(
            "preparation.inputs", source_manifest_sha256=frozen,
            staged_tree_oid=before_index, changed_paths=paths, producers=producers,
        )
        if mode == "generate":
            for producer in producers:
                run_producer(repository, producer, False, runner)
            stable = tree_snapshot(repository, outputs)
            for producer in producers:
                run_producer(repository, producer, False, runner)
                current = tree_snapshot(repository, outputs)
                if current != stable:
                    raise RuntimeError(
                        f"Generated inputs did not converge after {producer[1]} for {producer[0]}"
                    )
        else:
            for producer in producers:
                run_producer(repository, producer, True, runner)
        if git(repository, "write-tree") != before_index:
            raise RuntimeError("A preparation producer changed the staged Git index")
        if input_digest(repository, inputs) != frozen:
            operation.finish("inputs-invalidated", 1)
            raise RuntimeError("Validation inputs changed during preparation")
        diff = subprocess.run(
            ["git", "diff", "--binary", "--", *outputs], cwd=repository,
            check=True, capture_output=True,
        ).stdout
        write_private(diff_output, diff)
        manifest = {
            "schema": 1,
            "operation_id": operation.id,
            "mode": mode,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "repository": str(repository.resolve()),
            "head_oid": git(repository, "rev-parse", "HEAD"),
            "staged_tree_oid": before_index,
            "source_manifest_sha256": frozen,
            "changed_paths": paths,
            "selected_producers": [{"sample": sample, "producer": kind} for sample, kind in producers],
            "generated_outputs": tree_snapshot(repository, outputs),
            "intended_diff": str(diff_output.resolve()),
            "toolchain": {
                "host": [platform.system(), platform.machine()],
                "cargo": command_output(repository, ["cargo", "--version"]),
                "rustc": command_output(repository, ["rustc", "-Vv"]),
            },
            "status": "passed",
        }
        write_private(output, (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode())
        operation.event(
            "artifact.published", artifact_kind="validation-input-manifest",
            path=str(output.resolve()), source_manifest_sha256=frozen,
            intended_diff=str(diff_output.resolve()),
        )
        return manifest


def write_private(path: Path, contents: bytes) -> None:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "wb") as target:
            target.write(contents)
        os.replace(temporary, path)
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def command_output(repository: Path, command: list[str]) -> str:
    return subprocess.run(command, cwd=repository, check=True, capture_output=True, text=True).stdout.strip()


def file_digest(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def git(repository: Path, *arguments: str) -> str:
    return command_output(repository, ["git", *arguments])


def nul_paths(repository: Path, *arguments: str) -> list[str]:
    output = subprocess.run(["git", *arguments], cwd=repository, check=True, capture_output=True).stdout
    return [value.decode() for value in output.split(b"\0") if value]


def parse_arguments(arguments: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("check", "generate"))
    parser.add_argument("--sample", action="append", dest="samples")
    identity = uuid.uuid4()
    parser.add_argument("--output", type=Path, default=REPOSITORY_ROOT / f".logs/preparation/{identity}.json")
    parser.add_argument("--diff-output", type=Path, default=REPOSITORY_ROOT / f".logs/preparation/{identity}.patch")
    return parser.parse_args(arguments)


def main() -> None:
    arguments = parse_arguments()
    try:
        manifest = prepare(
            REPOSITORY_ROOT, arguments.mode, arguments.samples,
            arguments.output, arguments.diff_output,
        )
        print(f"Validation input manifest: {arguments.output.resolve()}")
        print(f"Selected generators: {len(manifest['selected_producers'])}")
    except (OSError, RuntimeError, subprocess.CalledProcessError, tomllib.TOMLDecodeError) as error:
        print(error, file=sys.stderr)
        raise SystemExit(1) from error


if __name__ == "__main__":
    main()
