[package]
name = "battlement-tictactoe-rules"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "battlement_rules"
crate-type = ["cdylib", "rlib"]

[dependencies]
battlement = { path = "../../../crates/battlement" }
battlement-native = { path = "../../../crates/battlement-native" }
fastrand = "2.3.0"

[dev-dependencies]
battlement-fake = { path = "../../../crates/battlement-fake" }

[workspace]
