[package]
name = "reactant"
version = "0.1.0"
description = "Declarative application facade for Battlement"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
battlement = { path = "../battlement" }
reactant-core.workspace = true
reactant-rules.workspace = true
reactant-ui.workspace = true

uuid.workspace = true
